const cities = [
  "Tokyo",
  "Jakarta",
  "Delhi",
  "Mumbai",
  "Manila",
  "Shanghai",
  "Sao Paulo",
  "Seoul",
  "Mexico City",
  "Guangzhou",
  "Beijing",
  "Cairo",
  "New York",
  "Kolkata",
  "Moscow",
  "Bangkok",
  "Buenos Aires",
  "Shenzhen",
  "Dhaka",
  "Lagos",
  "Istanbul",
  "Osaka",
  "Karachi",
  "Bangalore",
  "Tehran",
  "Kinshasa",
  "Ho Chi Minh City",
  "Los Angeles",
  "Rio de Janeiro",
  "Nanyang",
  "Chennai",
  "Chengdu",
  "Lahore",
  "Paris",
  "London",
  "Linyi",
  "Tianjin",
  "Shijiazhuang",
  "Baoding",
  "Zhoukou",
  "Lima",
  "Hyderabad",
  "Bogota",
  "Weifang",
  "Nagoya",
  "Wuhan",
  "Heze",
  "Ganzhou",
  "Tongshan",
  "Chicago",
  "Handan",
  "Luanda",
  "Fuyang",
  "Kuala Lumpur",
  "Jining",
  "Dongguan",
  "Hanoi",
  "Pune",
  "Chongqing",
  "Changchun",
  "Zhumadian",
  "Ningbo",
  "Onitsha",
  "Nanjing",
  "Hefei",
  "Ahmadabad",
  "Hong Kong",
  "Khartoum",
  "Nantong",
  "Yancheng",
  "Foshan",
  "Nanning",
  "Hengyang",
  "Xi'an",
  "Shenyang",
  "Tangshan",
  "Shaoyang",
  "Changsha",
  "Santiago",
  "Zhengzhou",
  "Zhanjiang",
  "Riyadh",
  "Cangzhou",
  "Dar es Salaam",
  "Maoming",
  "Huanggang",
  "Xinyang",
  "Shangrao",
  "Luoyang",
  "Bijie",
  "Yantai",
  "Quanzhou",
  "Hangzhou",
  "Miami",
  "Kunming",
  "Nanchong",
  "Zunyi",
  "Lu'an",
  "Yichun",
  "Taizhou",
  "Liaocheng",
  "Qujing",
  "Xiangyang",
  "Surat",
  "Baghdad",
  "Qingdao",
  "Singapore",
  "Dallas",
  "Changde",
  "Dazhou",
  "Suzhou",
  "Philadelphia",
  "Jieyang",
  "Nairobi",
  "Nangandao",
  "Ankara",
  "Tai'an",
  "Yulin",
  "Dezhou",
  "Houston",
  "Atlanta",
  "Rangoon",
  "Toronto",
  "Suihua",
  "Washington",
  "Qiqihar",
  "Jinhua",
  "Saint Petersburg",
  "Shantou",
  "Sydney",
  "Weinan",
  "Suqian",
  "Guadalajara",
  "Suzhou",
  "Fuzhou",
  "Zhaotong",
  "Pudong",
  "Yongzhou",
  "Belo Horizonte",
  "Zhangzhou",
  "Bozhou",
  "Melbourne",
  "Nanchang",
  "Xianyang",
  "Taizhou",
  "Surabaya",
  "Abidjan",
  "Ji'an",
  "Mianyang",
  "Shaoxing",
  "Alexandria",
  "Yuncheng",
  "Pingdingshan",
  "Huai'an",
  "Xinpu",
  "Guilin",
  "Huaihua",
  "Jiujiang",
  "Anqing",
  "Boston",
  "Huanglongsi",
  "Xiaoganzhan",
  "Changzhou",
  "Barcelona",
  "Chenzhou",
  "Wuxi",
  "Zibo",
  "Jiaxing",
  "Dalian",
  "Harbin",
  "Yangzhou",
  "Yibin",
  "Jiangmen",
  "Johannesburg",
  "Meizhou",
  "Chifeng",
  "Casablanca",
  "Guiyang",
  "Langfang",
  "Zhangjiakou",
  "Izmir",
  "Linfen",
  "Wenzhou",
  "Monterrey",
  "Luzhou",
  "Jiangguanchi",
  "Neijiang",
  "Phoenix",
  "Yanjiang",
  "Yiyang",
  "Zhaoqing",
  "Hengshui",
  "Guigang",
  "Xiaoxita",
  "Xiamen",
  "Chuzhou",
  "Fuzhou",
  "Amman",
  "Jeddah",
  "Sialkot City",
  "Huizhou",
  "Qingyuan",
  "Zhuzhou",
  "Wuhu",
  "Hechi",
  "Seattle",
  "Loudi",
  "Binzhou",
  "Liuzhou",
  "Yokohama",
  "Baojishi",
  "Guang'an",
  "Hanzhong",
  "Kabul",
  "Zaozhuang",
  "Berlin",
  "Anshan",
  "Deyang",
  "Lanzhou",
  "Chengde",
  "San Francisco",
  "Puyang",
  "Suining",
  "Jiaozuo",
  "Bengbu",
  "Montreal",
  "Detroit",
  "Baicheng",
  "Busan",
  "Algiers",
  "Qincheng",
  "Taiyuan",
  "Lucknow",
  "Chaoyang",
  "Hechi",
  "Leshan",
  "Yulinshi",
  "Siping",
  "Madrid",
  "Jinan",
  "Shiyan",
  "Changzhi",
  "San Diego",
  "Faisalabad",
  "Santa Cruz",
  "Bazhou",
  "Zhongshan",
  "Zhenjiang",
  "Urumqi",
  "Tongliao",
  "Heyuan",
  "Tongren",
  "Qinzhou",
  "Jaipur",
  "Xinzhou",
  "Addis Ababa",
  "Giza",
  "Meishan",
  "Brasilia",
  "Mashhad",
  "Jinzhou",
  "Tieling",
  "Shaoguan",
  "Shanwei",
  "Minneapolis",
  "Kyiv",
  "Sanaa",
  "Quezon City",
  "Dingxi",
  "Salvador",
  "Incheon",
  "Bursa",
  "Ningde",
  "Tampa",
  "Daqing",
  "Birmingham",
  "Putian",
  "Huzhou",
  "Wuzhou",
  "Denver",
  "Rome",
  "La Paz",
  "Pyongyang",
  "Kano",
  "Taichung",
  "Omdurman",
  "Zigong",
  "Qinhuangdao",
  "Mudanjiang",
  "Huludao",
  "Kaohsiung",
  "Xiangtan",
  "Guayaquil",
  "Rizhao",
  "Manchester",
  "Cawnpore",
  "Baotou",
  "Taipei",
  "Nanping",
  "Longyan",
  "Ibadan",
  "Hohhot",
  "Chaozhou",
  "Antananarivo",
  "Longba",
  "Weihai",
  "Chattogram",
  "Santo Domingo",
  "Xuanzhou",
  "Sanming",
  "Brooklyn",
  "Medellin",
  "Brisbane",
  "Baoshan",
  "Dubai",
  "Luohe",
  "Qinbaling",
  "Mirzapur",
  "Guangyuan",
  "Cali",
  "Daegu",
  "Fortaleza",
  "Guatemala City",
  "Yaounde",
  "Douala",
  "Jilin",
  "Lianshan",
  "Lincang",
  "Antalya",
  "Tashkent",
  "Huangshi",
  "Bandung",
  "Nagpur",
  "Dandong",
  "Huainan",
  "Shangzhou",
  "Bekasi",
  "Ghaziabad",
  "Tijuana",
  "Jiamusi",
  "Yangjiang",
  "Accra",
  "Yuxi",
  "Fushun",
  "Anshun",
  "Vancouver",
  "Tangerang",
  "Konya",
  "Queens",
  "Yingkou",
  "Adana",
  "Medan",
  "Sanmenxia",
  "Indore",
  "Ma'anshan",
  "Pingliang",
  "Quzhou",
  "Baku",
  "Gaoping",
  "Huaibei",
  "Xining",
  "Yan'an",
  "Havana",
  "Phnom Penh",
  "Fukuoka",
  "Mogadishu",
  "Jincheng",
  "Lishui",
  "Qingyang",
  "Riverside",
  "Baltimore",
  "Haiphong",
  "Las Vegas",
  "Laibin",
  "Rawalpindi",
  "Kumasi",
  "Portland",
  "Vadodara",
  "Perth",
  "Puning",
  "San Antonio",
  "Haikou",
  "Vishakhapatnam",
  "Gaziantep",
  "Minsk",
  "St. Louis",
  "Bamako",
  "Quito",
  "Pingxiang",
  "Chongzuo",
  "Sanliurfa",
  "Kananga",
  "Peshawar",
  "Sapporo",
  "Jixi",
  "Caracas",
  "Fuxin",
  "Leeds",
  "Sacramento",
  "Blantyre",
  "Tainan",
  "Bucharest",
  "Wuwei",
  "Bhopal",
  "Curitiba",
  "Xiping",
  "Asuncion",
  "Saidu Sharif",
  "Vienna",
  "Aleppo",
  "Hamburg",
  "Meru",
  "Brazzaville",
  "Orlando",
  "Mersin",
  "Almaty",
  "Barranquilla",
  "Kyoto",
  "Manaus",
  "Liaoyang",
  "Baiyin",
  "San Jose",
  "Warsaw",
  "Shengli",
  "Lubumbashi",
  "Damascus",
  "Shuyangzha",
  "Shangqiu",
  "Esfahan",
  "Budapest",
  "Heihe",
  "Lusaka",
  "Diyarbakir",
  "Chinchvad",
  "Shuozhou",
  "Vitoria",
  "Cleveland",
  "Pittsburgh",
  "Mecca",
  "Patna",
  "Mosul",
  "Austin",
  "Sanzhou",
  "Conakry",
  "Kampala",
  "Ecatepec",
  "Cincinnati",
  "Makassar",
  "Yushan",
  "Ludhiana",
  "Newcastle",
  "Depok",
  "Zhongli",
  "Kansas City",
  "Rabat",
  "Ouagadougou",
  "Davao",
  "Manhattan",
  "Semarang",
  "Yinchuan",
  "Multan",
  "Caloocan City",
  "Harare",
  "Novosibirsk",
  "Chengtangcun",
  "Agra",
  "Karaj",
  "Indianapolis",
  "Jingdezhen",
  "Puebla",
  "Kalyan",
  "Madurai",
  "Gujranwala",
  "Benxi",
  "Jamshedpur",
  "Zhuhai",
  "Recife",
  "Columbus",
  "Tabriz",
  "Santiago",
  "Maracaibo",
  "Beihai",
  "Shuangyashan",
  "Kobe",
  "Charlotte",
  "Yucheng",
  "Changshu",
  "Ximeicun",
  "Jianguang",
  "Gwangju",
  "Xushan",
  "Guiping",
  "Nasik",
  "Porto Alegre",
  "Zhangjiajie",
  "Valencia",
  "Virginia Beach",
  "Daejeon",
  "Munich",
  "Yekaterinburg",
  "Auckland",
  "Yunfu",
  "Huangshan",
  "Huazhou",
  "Shiraz",
  "Leon de los Aldama",
  "Pizhou",
  "Palembang",
  "Kharkiv",
  "Kawanakajima",
  "Lianjiang",
  "Chizhou",
  "Leizhou",
  "Guyuan",
  "Rui'an",
  "Birstall",
  "Muscat",
  "Hebi",
  "Jingling",
  "Bronx",
  "The Hague",
  "Owerri",
  "Sharjah",
  "Faridabad",
  "Ulaanbaatar",
  "Goiania",
  "Belem",
  "Kayseri",
  "Yueqing",
  "Belgrade",
  "Pingdu",
  "Aurangabad",
  "Yutan",
  "Wenling",
  "Islamabad",
  "Milwaukee",
  "Milan",
  "Sofia",
  "Adelaide",
  "Samsun",
  "Rajkot",
  "Khulna",
  "Cordoba",
  "Guarulhos",
  "Juarez",
  "Prague",
  "Montevideo",
  "Mbuji-Mayi",
  "Fuqing",
  "Xintai",
  "Doha",
  "Saitama",
  "Hiroshima",
  "Meerut",
  "Yushu",
  "Rongcheng",
  "Yangquan",
  "Haicheng",
  "Gaozhou",
  "Yingtan",
  "Huaiyin",
  "Wuzhong",
  "Jabalpur",
  "Thane",
  "Zhangye",
  "Rucheng",
  "Nizhniy Novgorod",
  "Comayaguela",
  "Yangshe",
  "Shaoyang",
  "Dhanbad",
  "Yichun",
  "Laiwu",
  "Kazan",
  "Dayan",
  "Suwon",
  "Jiangyin",
  "Yongcheng",
  "Calgary",
  "Can Tho",
  "Abuja",
  "Yiwu",
  "Mandalay",
  "Beidao",
  "Al Basrah",
  "Shuangshui",
  "Sevilla",
  "Vila Velha",
  "Allahabad",
  "Varanasi",
  "Tunis",
  "Chelyabinsk",
  "Mombasa",
  "Providence",
  "Qom",
  "Maiduguri",
  "Maputo",
  "Rosario",
  "Benin City",
  "Xinyu",
  "Ahvaz",
  "Dublin",
  "Jacksonville",
  "Medina",
  "Srinagar",
  "Omsk",
  "Huazhou",
  "Cilacap",
  "Xiantao",
  "Bandar Lampung",
  "Samara",
  "Guankou",
  "Ulsan",
  "Dingzhou",
  "Campinas",
  "Lianyuan",
  "Rongcheng",
  "Kaiyuan",
  "Nay Pyi Taw",
  "Dakar",
  "Zhuji",
  "Zapopan",
  "Leiyang",
  "Dadukou",
  "Quetta",
  "Amritsar",
  "Callao",
  "Aligarh",
  "Yingchuan",
  "Tegucigalpa",
  "Ciudad Nezahualcoyotl",
  "Tripoli",
  "Rostov",
  "Nezahualcoyotl",
  "Bhiwandi",
  "Zhoushan",
  "Tbilisi",
  "Ufa",
  "Fes",
  "Bien Hoa",
  "Mexicali",
  "Gwalior",
  "Ankang",
  "Ikare",
  "Hegang",
  "Salt Lake City",
  "Bhilai",
  "Yuyao",
  "N'Djamena",
  "Hanchuan",
  "Gongzhuling",
  "Copenhagen",
  "Irbid",
  "Haora",
  "Cologne",
  "Krasnoyarsk",
  "Yicheng",
  "Mizhou",
  "Nashville",
  "Yerevan",
  "Ranchi",
  "Nur-Sultan",
  "Nouakchott",
  "Vereeniging",
  "Richmond",
  "Sao Luis",
  "San Pedro Sula",
  "Taixing",
  "Memphis",
  "Goyang",
  "Bezwada",
  "Edmonton",
  "Xishan",
  "Barquisimeto",
  "Sendai",
  "Voronezh",
  "Perm",
  "Changwon",
  "Zhongwei",
  "Shouguang",
  "Bogor",
  "Raleigh",
  "Cartagena",
  "Chandigarh",
  "Bishkek",
  "Amsterdam",
  "Matola",
  "Ogbomoso",
  "Ashgabat",
  "E'zhou",
  "Maceio",
  "Niamey",
  "Managua",
  "Patam",
  "Tekirdag",
  "Linhai",
  "Shubra al Khaymah",
  "Monrovia",
  "Wafangdian",
  "Zhongxiang",
  "Shymkent",
  "New Orleans",
  "Volgograd",
  "Port-au-Prince",
  "Mysore",
  "Odesa",
  "Kathmandu",
  "Raipur",
  "Nice",
  "Arequipa",
  "Port Harcourt",
  "Rotterdam",
  "Louisville",
  "Zaoyang",
  "Shuizhai",
  "Kota",
  "Abu Dhabi",
  "Stockholm",
  "Ottawa",
  "Asmara",
  "Freetown",
  "Jerusalem",
  "Panama City",
  "Lome",
  "Libreville",
  "Zagreb",
  "Dushanbe",
  "Lilongwe",
  "Cotonou",
  "Vientiane",
  "Colombo",
  "Kigali",
  "Pretoria",
  "Bangui",
  "Winnipeg",
  "Quebec City",
  "Riga",
  "Oslo",
  "Chisinau",
  "Athens",
  "Bujumbura",
  "Helsinki",
  "Skopje",
  "Kuwait City",
  "Kingston",
  "Vilnius",
  "San Salvador",
  "Djibouti",
  "Lisbon",
  "Kitchener",
  "Tallinn",
  "Cape Town",
  "Bratislava",
  "Tirana",
  "Canberra",
  "Wellington",
  "Beirut",
  "Dodoma",
  "Halifax",
  "Bissau",
  "Juba",
  "Port Moresby",
  "Yamoussoukro",
  "Victoria",
  "Maseru",
  "Nicosia",
  "Windhoek",
  "Porto-Novo",
  "Sucre",
  "San Jose",
  "Ljubljana",
  "Sarajevo",
  "Nassau",
  "Bloemfontein",
  "Gaborone",
  "Paramaribo",
  "Dili",
  "Pristina",
  "Georgetown",
  "Malabo",
  "Brussels",
  "Male",
  "Podgorica",
  "Manama",
  "Port Louis",
  "New Delhi",
  "Bern",
  "Reykjavik",
  "Praia",
  "Luxembourg",
  "Sri Jayewardenepura Kotte",
  "Bridgetown",
  "Moroni",
  "Thimphu",
  "Mbabane",
  "Honiara",
  "Suva",
  "Castries",
  "Sao Tome",
  "Port-Vila",
  "Bandar Seri Begawan",
  "Monaco",
  "Gitega",
  "Port of Spain",
  "Apia",
  "Vaduz",
  "Banjul",
  "Tarawa",
  "Victoria",
  "Majuro",
  "Kingstown",
  "Nuku`alofa",
  "Saint John's",
  "Andorra la Vella",
  "Belmopan",
  "Roseau",
  "Basseterre",
  "Pago Pago",
  "Valletta",
  "Palikir",
  "Funafuti",
  "Lobamba",
  "Saint George's",
  "San Marino",
  "Al Quds",
  "Capitol Hill",
  "Hagta",
  "Ngerulmud",
  "Bareilly",
  "Quang Ha",
  "Kitaku",
  "Jodhpur",
  "Xingcheng",
  "Dongtai",
  "Joinvile",
  "Yingcheng",
  "Dnipro",
  "Glasgow",
  "Chiba",
  "Danyang",
  "Natal",
  "Naples",
  "Zhaodong",
  "Xibeijie",
  "Kirkuk",
  "Huilong",
  "Tongjin",
  "Oklahoma City",
  "Toulouse",
  "Denizli",
  "Dispur",
  "Coimbatore",
  "Luocheng",
  "Guwahati",
  "Shima",
  "Songnam",
  "Solapur",
  "Tangier",
  "Anqiu",
  "Feicheng",
  "Taishan",
  "Meishan",
  "Kisangani",
  "Khartoum North",
  "Aguascalientes",
  "Marrakech",
  "Nada",
  "Donetsk",
  "Taihecun",
  "Wuchuan",
  "Trujillo",
  "Cebu City",
  "Taihe",
  "Olinda",
  "Bridgeport",
  "Trichinopoly",
  "Xin'an",
  "Padang",
  "Qingzhou",
  "Buffalo",
  "Xinyi",
  "Lichuan",
  "Daye",
  "Fort Worth",
  "Zhuanghe",
  "Hartford",
  "Ad Dammam",
  "Bucheon",
  "Lhasa",
  "Homs",
  "Jiaozhou",
  "Merida",
  "Dengtalu",
  "Zaria",
  "Hubli",
  "Abeokuta",
  "Tucson",
  "Krasnodar",
  "Natal",
  "Novo Hamburgo",
  "Chihuahua",
  "Klang",
  "Turin",
  "Jos",
  "Laiyang",
  "Jalandhar",
  "Campo Grande",
  "Sale",
  "Barinas",
  "Marseille",
  "Kaifeng Chengguanzhen",
  "Eskisehir",
  "Gaomi",
  "Ipoh",
  "Hai'an",
  "Liverpool",
  "Zamboanga City",
  "Oran",
  "Southampton",
  "Weichanglu",
  "Pekanbaru",
  "Portsmouth",
  "Leping",
  "Erbil",
  "Kermanshah",
  "Hailun",
  "Yangchun",
  "Macheng",
  "Ilorin",
  "Teresina",
  "Omaha",
  "Yuci",
  "Saratov",
  "Iguacu",
  "El Paso",
  "Denpasar",
  "Dehui",
  "Naucalpan de Juarez",
  "Bhubaneshwar",
  "Tongchuan",
  "Cheongju",
  "Warri",
  "Pointe-Noire",
  "Rongjiawan",
  "San Luis Potosi",
  "Butterworth",
  "Bhayandar",
  "Renqiu",
  "Toluca",
  "Honolulu",
  "Queretaro",
  "Xindi",
  "Wu'an",
  "Sao Bernardo do Campo",
  "Hermosillo",
  "Wutong",
  "Taguig City",
  "Saltillo",
  "Gaoyou",
  "Hejian",
  "Yiyang",
  "Puxi",
  "Zijinglu",
  "Xiashi",
  "Trabzon",
  "Joao Pessoa",
  "Dongyang",
  "McAllen",
  "Valencia",
  "Qingping",
  "Niigata",
  "Hamamatsu",
  "Morelia",
  "Pasig City",
  "Moradabad",
  "Culiacan",
  "Xiangxiang",
  "Malang",
  "Xingyi",
  "Chaohucun",
  "Fuyang",
  "Antipolo",
  "Nottingham",
  "Cencheng",
  "Krakow",
  "Hempstead",
  "Erzurum",
  "Al `Ayn",
  "Songzi",
  "Laixi",
  "Zhongba",
  "Qingnian",
  "Albuquerque",
  "Kaduna",
  "Tlalnepantla",
  "Xinhualu",
  "Guangshui",
  "Frankfurt",
  "Samarinda",
  "Changhua",
  "Pietermaritzburg",
  "Hungnam",
  "Kolhapur",
  "Ciudad Guayana",
  "Cucuta",
  "Licheng",
  "Thiruvananthapuram",
  "Tyumen",
  "San Cristobal",
  "Zaporizhzhia",
  "Cancun",
  "Kumamoto",
  "Chengguan",
  "Nehe",
  "Sokoto",
  "Birmingham",
  "Zunhua",
  "Orumiyeh",
  "Oyo",
  "Wugang",
  "Shuangqiao",
  "Rennes",
  "Sizhan",
  "Langzhong",
  "Bristol",
  "Qian'an",
  "Lviv",
  "Zouping",
  "Bremen",
  "Reynosa",
  "An Najaf",
  "Sagamihara",
  "Guli",
  "Sarasota",
  "Okayama",
  "Mississauga",
  "Lingbao Chengguanzhen",
  "Anlu",
  "Wusong",
  "Dayton",
  "Enugu",
  "George Town",
  "Jaboatao",
  "Santo Andre",
  "Xichang",
  "Soledad",
  "Chengxiang",
  "Tolyatti",
  "Saharanpur",
  "Warangal",
  "Osasco",
  "Dashiqiao",
  "Latakia",
  "Rochester",
  "Fresno",
  "Banjarmasin",
  "Salem",
  "Changsha",
  "Grenoble",
  "Shishi",
  "Guadalupe",
  "Aracaju",
  "Bauchi",
  "Hamilton",
  "Lodz",
  "Miluo Chengguanzhen",
  "Gaizhou",
  "Shizuoka",
  "Malegaon",
  "Karbala'",
  "Leling",
  "Sao Jose dos Campos",
  "Jianshe",
  "Acapulco de Juarez",
  "Sheffield",
  "Jingcheng",
  "City of Paranaque",
  "Kochi",
  "Allentown",
  "Bahawalpur",
  "Tasikmalaya",
  "Macau",
  "Torreon",
  "Xinmin",
  "Shanhu",
  "Zhongshu",
  "Xigaze",
  "Gold Coast",
  "Palermo",
  "Cagayan de Oro",
  "Gorakhpur",
  "Pinghu",
  "Guankou",
  "Tulsa",
  "Yatou",
  "Songyang",
  "Cape Coral",
  "Ch'ongjin",
  "Sao Jose dos Pinhais",
  "Puyang Chengguanzhen",
  "Qionghu",
  "Yanshi Chengguanzhen",
  "Ribeirao Preto",
  "Dasmarinas",
  "Huambo",
  "Wenchang",
  "Shulan",
  "Catia La Mar",
  "Bouake",
  "As Sulaymaniyah",
  "Hwasu-dong",
  "Jeonju",
  "Durango",
  "Shimoga",
  "Ansan",
  "Bulawayo",
  "Xiping",
  "Sanhe",
  "Guntur",
  "Dali",
  "Concord",
  "Tiruppur",
  "Ch'onan",
  "Zaragoza",
  "Izhevsk",
  "Guixi",
  "Honcho",
  "Sorocaba",
  "Villahermosa",
  "Petaling Jaya",
  "Wuxue",
  "Utrecht",
  "Kikwit",
  "Colorado Springs",
  "Valenzuela",
  "Gaobeidian",
  "Qufu",
  "Ruiming",
  "Wroclaw",
  "Rasht",
  "Nantes",
  "Stuttgart",
  "Al Hufuf",
  "Xinshi",
  "Cochabamba",
  "Barnaul",
  "Tripoli",
  "Jin'e",
  "Benghazi",
  "Kryvyy Rih",
  "Yanggok",
  "Changping",
  "Raurkela",
  "Halwan",
  "Charleston",
  "Chimalhuacan",
  "Xinxing",
  "Suohe",
  "Mangalore",
  "Zhuangyuan",
  "Ulyanovsk",
  "Irkutsk",
  "Nanded",
  "Bacoor",
  "Pontianak",
  "Bazhou",
  "Springfield",
  "Turpan",
  "Dusseldorf",
  "Xingtai",
  "Meihekou",
  "Jurong",
  "Zhugang",
  "Khabarovsk",
  "Xinji",
  "Hamhung",
  "Serang",
  "Buraydah",
  "Ta`izz",
  "Montpellier",
  "San Miguel de Tucuman",
  "Yaroslavl",
  "Zhangshu",
  "Grand Rapids",
  "Vladivostok",
  "Kuantan",
  "Cuttack",
  "Jambi",
  "Zhuozhou",
  "Uberlandia",
  "Gothenburg",
  "Tianchang",
  "Canoas",
  "Sargodha",
  "Las Pinas City",
  "Cimahi",
  "Kawaguchi",
  "Tuxtla",
  "Balikpapan",
  "Qamdo",
  "Durban",
  "Kagoshima",
  "General Santos",
  "Chanda",
  "Al Hillah",
  "Makhachkala",
  "Mar del Plata",
  "Brampton",
  "Luocheng",
  "Mission Viejo",
  "Dortmund",
  "Chuxiong",
  "Makati City",
  "Albany",
  "Shah Alam",
  "Knoxville",
  "Essen",
  "Cuiaba",
  "Shangzhi",
  "Botou",
  "Bucaramanga",
  "Anyang",
  "Genoa",
  "Kuiju",
  "Tlaquepaque",
  "Hachioji",
  "Dehra Dun",
  "At Ta'if",
  "San Jose del Monte",
  "Bakersfield",
  "Ogden",
  "Xiulin",
  "Fu'an",
  "Malaga",
  "Tomsk",
  "Kerman",
  "Kingston upon Hull",
  "Al Mahallah al Kubra",
  "Luofeng",
  "Lingyuan",
  "Baton Rouge",
  "Pereira",
  "Ciudad Bolivar",
  "Durgapur",
  "Orenburg",
  "Shenzhou",
  "Asansol",
  "Bacolod",
  "Akron",
  "New Haven",
  "Zhenzhou",
  "Surakarta",
  "Tlajomulco de Zuniga",
  "Jieshou",
  "Lanxi",
  "Zahedan",
  "Dangyang",
  "Columbia",
  "Kemerovo",
  "Dresden",
  "Uyo",
  "Bhavnagar",
  "Luanzhou",
  "Veracruz",
  "Novokuznetsk",
  "Nellore",
  "Chiclayo",
  "Al Hudaydah",
  "Eslamshahr",
  "Cabinda",
  "Amravati",
  "Korla",
  "Huanghua",
  "Xingcheng",
  "Wancheng",
  "Kaiyuan",
  "Leipzig",
  "Fengcheng",
  "Ajmer",
  "Sihui",
  "Tinnevelly",
  "Fuding",
  "Maturin",
  "An Nasiriyah",
  "Al Hillah",
  "Ibague",
  "Hannover",
  "Poznan",
  "Ryazan",
  "Panshi",
  "Kassala",
  "Chang'an",
  "Wencheng",
  "Shashi",
  "Aksu",
  "Salta",
  "Kimhae",
  "Astrakhan",
  "Mingguang",
  "Naberezhnyye Chelny",
  "Antwerp",
  "Bikaner",
  "Agartala",
  "Xalapa",
  "Ndola",
  "Hamadan",
  "Villavicencio",
  "Ailan Mubage",
  "Ensenada",
  "Lyon",
  "Bac Ninh",
  "Ciudad Apodaca",
  "Santa Teresa del Tuy",
  "Londrina",
  "Penza",
  "Heroica Matamoros",
  "Port Said",
  "New Mirpur",
  "Yucheng",
  "Bello",
  "Meknes",
  "Nuremberg",
  "Pohang",
  "Utsunomiya",
  "Anda",
  "Jinghong",
  "Liaoyuan",
  "Mesa",
  "Surrey",
  "Cuautitlan Izcalli",
  "Ujjain",
  "Santa Marta",
  "Beining",
  "Hai Duong",
  "Carrefour",
  "Homyel'",
  "Leicester",
  "Yanji",
  "Benguela",
  "Yicheng",
  "Tabuk",
  "Lipetsk",
  "Ulhasnagar",
  "Matsuyama",
  "Muntinlupa City",
  "Kashgar",
  "Linghai",
  "Aden",
  "Jhansi",
  "Kitwe",
  "Aba",
  "Palm Bay",
  "Pingtung",
  "Samarkand",
  "Davangere",
  "Ichikawa",
  "Jammu",
  "Mazatlan",
  "Higashi-osaka",
  "Ile-Ife",
  "Kirov",
  "Madinat as Sadis min Uktubar",
  "Qaraghandy",
  "Mazatan",
  "Duisburg",
  "Mykolaiv",
  "Matsudo",
  "Provo",
  "Meicheng",
  "Niteroi",
  "Rouen",
  "Oujda-Angad",
  "Johor Bahru",
  "Worcester",
  "Hongjiang",
  "Chimbote",
  "Dengtacun",
  "Ixtapaluca",
  "Zhijiang",
  "Chengjiao",
  "Beipiao",
  "Murrieta",
  "Kota Bharu",
  "Heshan",
  "Ciudad Lopez Mateos",
  "Vinh",
  "Tultitlan de Mariano Escobedo",
  "Duyun",
  "Encheng",
  "Nishinomiya-hama",
  "Kandahar",
  "Cheboksary",
  "Yuanping",
  "Port Sudan",
  "Valledupar",
  "Edinburgh",
  "Belgaum",
  "Tula",
  "Taozhou",
  "Suez",
  "Shahe",
  "Yazd",
  "Nazret",
  "Gaoping",
  "Brookhaven",
  "Greenville",
  "Arak",
  "San Nicolas de los Garza",
  "Gulbarga",
  "Juiz de Fora",
  "Dunhua",
  "Feira de Santana",
  "Jiaji",
  "Az Zarqa'",
  "Americana",
  "Ardabil",
  "Sylhet",
  "Wichita",
  "Toledo",
  "Kaihua",
  "Caerdydd",
  "Jamnagar",
  "Fuyuan",
  "Dhulia",
  "Nampula",
  "Gaya",
  "Piraeus",
  "Oita",
  "Florianopolis",
  "Chiniot",
  "Jiannan",
  "Wuhai",
  "Kaliningrad",
  "Sukkur",
  "Nangong",
  "Staten Island",
  "San Juan",
  "Vila Velha",
  "Macapa",
  "Des Moines",
  "Piura",
  "Jiaojiangcun",
  "Laohekou",
  "Fujin",
  "Beian",
  "Celaya",
  "Xiaoyi",
  "Strasbourg",
  "Lanus",
  "Qingzhen",
  "Jiangshan",
  "Ba`qubah",
  "Tamale",
  "Gdansk",
  "Kanazawa",
  "Manado",
  "Jinchang",
  "Calabar",
  "Fukuyama",
  "Long Beach",
  "Malatya",
  "Hue",
  "Jalgaon",
  "Port St. Lucie",
  "Maua",
  "Monteria",
  "Tel Aviv-Yafo",
  "Xicheng",
  "Marikina City",
  "Pyeongtaek",
  "Kurnool",
  "Sfax",
  "City of Calamba",
  "Denton",
  "Ar Ramadi",
  "Melaka",
  "Volta Redonda",
  "Jian'ou",
  "Shenmu",
  "Huadian",
  "Taoyuan District",
  "Iloilo",
  "Kota Kinabalu",
  "Minzhu",
  "Rajshahi",
  "Tanta",
  "Balashikha",
  "Udaipur",
  "Kursk",
  "Mariupol",
  "Bukavu",
  "Hsinchu",
  "Barcelona",
  "Constantine",
  "Tanbei",
  "Ado-Ekiti",
  "Batman",
  "Pasay City",
  "Madison",
  "Pingquan",
  "Baisha",
  "Bellary",
  "Santiago de Cuba",
  "Yongji",
  "Reno",
  "Danjiangkou",
  "Kahramanmaras",
  "Sao Jose do Rio Preto",
  "Andijon",
  "Harrisburg",
  "Nancy",
  "Al Mansurah",
  "Machida",
  "Ning'an",
  "Beira",
  "Little Rock",
  "Zurich",
  "Zhangjiakou Shi Xuanhua Qu",
  "Sunch'on",
  "Diadema",
  "Guangming",
  "Sangli",
  "Tuticorin",
  "Herat",
  "Kupang",
  "Larkana",
  "Jeju",
  "Bandar `Abbas",
  "Santos",
  "Stavropol",
  "Katsina",
  "Yogyakarta",
  "Calicut",
  "Zanjan",
  "Welkom",
  "Ulan-Ude",
  "Oakland",
  "Kashiwa",
  "Mazar-e Sharif",
  "Kashan",
  "Kenitra",
  "Khamis Mushayt",
  "Masan",
  "Cusco",
  "Sevastopol",
  "Mandaluyong City",
  "Kihung",
  "Toyota",
  "Akola",
  "Yan'an Beilu",
  "Agadir",
  "Mogi das Cruzes",
  "Durham",
  "Likasi",
  "Laval",
  "Winston-Salem",
  "Uijeongbu",
  "Tver",
  "Elazig",
  "Akure",
  "Kumi",
  "Hpa-An",
  "Bonita Springs",
  "Hailin",
  "Seremban",
  "Takamatsu",
  "Lecheng",
  "Zhengjiatun",
  "Luhansk",
  "Pencheng",
  "Magnitogorsk",
  "Angeles City",
  "El Obeid",
  "Dalai",
  "Xingren",
  "Palma",
  "Kolwezi",
  "Wenlan",
  "Indio",
  "Palm Coast",
  "Arusha",
  "Fenyang",
  "Toyama",
  "Paju",
  "Mataram",
  "Chattanooga",
  "Lapu-Lapu City",
  "Nagqu",
  "Kisumu",
  "Jayapura",
  "Fangting",
  "Nagasaki",
  "Spokane",
  "Shekhupura",
  "Sochi",
  "Bhagalpur",
  "Ipatinga",
  "Ivanovo",
  "Osogbo",
  "Imus",
  "Ciudad Obregon",
  "Turkmenabat",
  "Namangan",
  "Bryansk",
  "Basuo",
  "Taiping",
  "Maracay",
  "Murcia",
  "Jiexiu",
  "Mbale",
  "Taraz",
  "Asyut",
  "Santa Fe",
  "Campina Grande",
  "Szczecin",
  "Ghulja",
  "Syracuse",
  "Carapicuiba",
  "Gifu",
  "Quilon",
  "Jundiai",
  "Lancaster",
  "Eindhoven",
  "Sikar",
  "Tumkur",
  "Jiangjiafan",
  "Miyazaki",
  "Arlington",
  "Stockton",
  "Bhatpara",
  "Sandakan",
  "Hejin",
  "Thanh Hoa",
  "Muzaffarnagar",
  "Poughkeepsie",
  "Comilla",
  "Metz",
  "Campos",
  "Nha Trang",
  "Belgorod",
  "Yola",
  "Minamisuita",
  "San Lorenzo",
  "Ad Diwaniyah",
  "Hancheng",
  "Fuyu",
  "Bologna",
  "Karamay",
  "Kakinada",
  "Augusta",
  "Bhilwara",
  "Caxias do Sul",
  "Tieli",
  "Cilegon",
  "Baicheng",
  "Nizamabad",
  "Boise",
  "Tonala",
  "Okazaki",
  "Mwanza",
  "Aqtobe",
  "Plovdiv",
  "Oxnard",
  "Tetouan",
  "Florence",
  "Ha'il",
  "Yidu",
  "Lianzhou",
  "Scranton",
  "London",
  "Las Palmas",
  "Rio Branco",
  "Modesto",
  "Ichinomiya",
  "Brno",
  "Kissimmee",
  "Pasto",
  "Qazvin",
  "Irapuato",
  "Novi Sad",
  "Antofagasta",
  "Shihezi",
  "Shache",
  "Panihati",
  "Huancayo",
  "Aurora",
  "Malabon",
  "Parbhani",
  "Usulutan",
  "Youngstown",
  "Christchurch",
  "Hatay",
  "Iquitos",
  "Sivas",
  "Helixi",
  "A Coruna",
  "Manizales",
  "Manukau City",
  "Stoke-on-Trent",
  "Cumana",
  "Vinnytsia",
  "Rohtak",
  "Latur",
  "Toyohashi",
  "Sanandaj",
  "Nuevo Laredo",
  "Anguo",
  "Ambon",
  "Mandaue City",
  "Keelung",
  "Varna",
  "Lengshuijiang",
  "Rajapalaiyam",
  "Nagano",
  "Az Zubayr",
  "Al Qatif",
  "Cuernavaca",
  "Sanya",
  "Nicolas Romero",
  "Huichang",
  "Vitsyebsk",
  "Bauru",
  "Bochum",
  "Anapolis",
  "Coventry",
  "Zalantun",
  "Tecamac",
  "Jhang City",
  "Ciudad General Escobedo",
  "Wonsan",
  "Kocaeli",
  "Bengkulu",
  "Montes Claros",
  "Petion-Ville",
  "Shuanghejiedao",
  "Bydgoszcz",
  "Surgut",
  "Donostia",
  "Bobo-Dioulasso",
  "Umuahia",
  "Gedaref",
  "Palu",
  "Santa Rosa",
  "Pokhara",
  "Mahilyow",
  "Wudalianchi",
  "Sungai Petani",
  "Nam Dinh",
  "Sinuiju",
  "Hrodna",
  "Vladimir",
  "Sao Vicente",
  "Wakayama",
  "Yong'an",
  "Itaquaquecetuba",
  "Wuppertal",
  "Minatitlan",
  "Nizhniy Tagil",
  "Nara",
  "Hongzhai",
  "Bilbao",
  "Haarlem",
  "Pavlodar",
  "Gimpo",
  "Rahimyar Khan",
  "Van",
  "Corrientes",
  "San Pedro",
  "Arkhangelsk",
  "Licheng",
  "Cabimas",
  "Yakeshi",
  "Baguio City",
  "Ahmadnagar",
  "Fayetteville",
  "Koshigaya",
  "Holguin",
  "Qo`qon",
  "Anaheim",
  "Yingmen",
  "Piracicaba",
  "Khorramabad",
  "Rajahmundry",
  "Chita",
  "Sari",
  "Makiivka",
  "Chitungwiza",
  "Pensacola",
  "Victorville",
  "Tokorozawa",
  "Tanch'on",
  "Sumqayit",
  "Kusti",
  "Al `Amarah",
  "Cuddapah",
  "Simferopol",
  "Tarlac City",
  "Lancaster",
  "Greensboro",
  "Iligan",
  "East London",
  "Otsu",
  "Franca",
  "Kaluga",
  "Yeosu",
  "Corpus Christi",
  "Muzaffarpur",
  "Lublin",
  "Brest",
  "Lianran",
  "Alwar",
  "Baishan",
  "Kawagoe",
  "Farg`ona",
  "Tamuramachi-moriyama",
  "Brahmapur",
  "Buon Ma Thuot",
  "Binan",
  "Iwaki",
  "Semey",
  "Tarsus",
  "Randburg",
  "Tepic",
  "Jitpur",
  "Kaesong",
  "Beni",
  "Chinju",
  "Tangdong",
  "Butuan",
  "Reading",
  "Belfast",
  "Alicante",
  "Blida",
  "Hangu",
  "Yingzhong",
  "Vina del Mar",
  "Asahikawa",
  "Bielefeld",
  "Cuenca",
  "Fort Wayne",
  "Maebashi",
  "Lipa City",
  "Wad Medani",
  "Islip",
  "Sousse",
  "Kamarhati",
  "Thessaloniki",
  "Ganca",
  "Bilaspur",
  "Santa Ana",
  "Mymensingh",
  "Al Fayyum",
  "Flint",
  "Kendari",
  "Balikesir",
  "Az Zaqaziq",
  "Thai Nguyen",
  "Smolensk",
  "Wonju",
  "Maringa",
  "San Juan",
  "Dahuk",
  "Batangas",
  "Mathura",
  "Pelotas",
  "Bamiantong",
  "Kochi",
  "Patiala",
  "Gujrat",
  "Bonn",
  "Vung Tau",
  "Markham",
  "Saugor",
  "Roodepoort",
  "Gomez Palacio",
  "Volzhskiy",
  "Bari",
  "Bijapur",
  "Sukabumi",
  "Ulanhot",
  "Fayetteville",
  "Itajai",
  "Nakuru",
  "Yunzhong",
  "Al Fallujah",
  "Boa Vista",
  "Cluj-Napoca",
  "Malmo",
  "Gwangmyeongni",
  "Pucallpa",
  "Cordoba",
  "Kuching",
  "Zinder",
  "Naha",
  "Gonder",
  "Uberaba",
  "Jackson",
  "Mekele",
  "Kulti",
  "Santa Rosa",
  "Gonaives",
  "Lansing",
  "Binxian",
  "Newcastle",
  "Kurgan",
  "Kaiyuan",
  "Temara",
  "Uruapan",
  "Hotan",
  "Camaguey",
  "Ann Arbor",
  "San Salvador de Jujuy",
  "Timisoara",
  "Al Kut",
  "Tapachula",
  "Shahjanpur",
  "Cherepovets",
  "Poltava",
  "Henderson",
  "Maroua",
  "Kaech'on",
  "Asan",
  "Coatzacoalcos",
  "Huntsville",
  "Trichur",
  "General Trias",
  "Cirebon",
  "Tampico",
  "Lexington",
  "Boaco",
  "Oskemen",
  "Ca Mau",
  "Neiva",
  "Cabuyao",
  "Vologda",
  "Saransk",
  "Mobile",
  "Bor",
  "Munster",
  "Barddhaman",
  "Ksar El Kebir",
  "Karlsruhe",
  "Kasur",
  "Yakou",
  "Orel",
  "Safi",
  "Shahr-e Qods",
  "Vitoria da Conquista",
  "Hamah",
  "Guaruja",
  "Catania",
  "Purnea",
  "Fort Collins",
  "Port Elizabeth",
  "Alanya",
  "Asheville",
  "Santa Clarita",
  "Gorgan",
  "Porto Velho",
  "Quy Nhon",
  "Sambalpur",
  "Yokkaichi",
  "Chalco",
  "Mannheim",
  "Namp'o",
  "Shahriar",
  "Kasugai",
  "Sapele",
  "Blumenau",
  "Sariwon",
  "St. Catharines",
  "Matadi",
  "Niagara Falls",
  "Firozabad",
  "San Fernando",
  "St. Paul",
  "Vladikavkaz",
  "Yakutsk",
  "Minna",
  "Hisar",
  "Puerto La Cruz",
  "Ciudad del Este",
  "Podolsk",
  "Ciudad Victoria",
  "Akita",
  "Kumul",
  "Vaughan",
  "Oakashicho",
  "Pekalongan",
  "Adiyaman",
  "Vila Nova de Gaia",
  "Curepipe",
  "Cabanatuan City",
  "Oaxaca",
  "Armenia",
  "Wollongong",
  "Brest",
  "Awka",
  "Iksan",
  "Taubate",
  "Antioch",
  "Lakeland",
  "Cadiz",
  "Soc Trang",
  "Awasa",
  "Mardan",
  "Popayan",
  "Praia Grande",
  "Qianzhou",
  "Cotabato",
  "Bidar",
  "Bialystok",
  "Merida",
  "Murmansk",
  "Afyonkarahisar",
  "Valladolid",
  "Jember",
  "Bahia Blanca",
  "Iskenderun",
  "Al Mubarraz",
  "Petropolis",
  "Al Kharj",
  "Rampur",
  "Najran",
  "Chernihiv",
  "Yangsan",
  "Vigo",
  "Oyster Bay",
  "Valparaiso",
  "Augsburg",
  "Mbeya",
  "Limeira",
  "Rangpur",
  "Ponta Grossa",
  "Shiliguri",
  "Aksaray",
  "Navotas",
  "Corum",
  "Bali",
  "Ismailia",
  "Panipat",
  "Cagliari",
  "Delmas",
  "Batna",
  "Kunp'o",
  "Tambov",
  "Iasi",
  "Thies",
  "Makurdi",
  "Morioka",
  "Kherson",
  "Groznyy",
  "Hong'an",
  "Bafoussam",
  "Resistencia",
  "Brasov",
  "Juliaca",
  "Graz",
  "Karimnagar",
  "Setif",
  "Trenton",
  "Kaunas",
  "Mulhouse",
  "Hulin",
  "Sekondi",
  "Lincoln",
  "Bhuj",
  "Ostrava",
  "Ichalkaranji",
  "Tirupati",
  "Springfield",
  "Punto Fijo",
  "Plano",
  "Irvine",
  "Fukushima",
  "Orleans",
  "Hospet",
  "Tacna",
  "Korhogo",
  "Constanta",
  "Haifa",
  "Coacalco",
  "Crato",
  "Limoges",
  "Davenport",
  "Coro",
  "Bago",
  "Fuquan",
  "Tongchuanshi",
  "Aizawl",
  "Taboao da Serra",
  "Sannai",
  "Huozhou",
  "Temuco",
  "Sterlitamak",
  "Rockford",
  "Tegal",
  "Ica",
  "Newark",
  "Jining",
  "Chuncheon",
  "Malard",
  "Pematangsiantar",
  "Long Xuyen",
  "Petrozavodsk",
  "South Bend",
  "Mingaora",
  "Barasat",
  "Shreveport",
  "Sincelejo",
  "Viet Tri",
  "Cherkasy",
  "Wiesbaden",
  "Kostroma",
  "Round Lake Beach",
  "Gyeongsan",
  "Katowice",
  "Shaowu",
  "Linxia Chengguanzhen",
  "Pachuca",
  "Dire Dawa",
  "Khmelnytskyi",
  "Aomori",
  "Owo",
  "Savannah",
  "Posadas",
  "Gatineau",
  "Windsor",
  "Tsu",
  "Myrtle Beach",
  "Mbandaka",
  "Tehuacan",
  "La Guaira",
  "Kunsan",
  "Nizhnevartovsk",
  "Chula Vista",
  "Ratlam",
  "Yeosu",
  "Crato",
  "Derby",
  "Kafr ad Dawwar",
  "Eugene",
  "Gijon",
  "Chiayi",
  "Fuchu",
  "Palmas",
  "Craiova",
  "Maradi",
  "Sorong",
  "Majene",
  "Bukhara",
  "Thai Binh",
  "Binjai",
  "Oral",
  "Brahmanbaria",
  "Sarta",
  "Imphal",
  "Plymouth",
  "Ichihara",
  "Santo Domingo de los Colorados",
  "Novorossiysk",
  "Santa Ana",
  "Zhytomyr",
  "Mito",
  "Gombe",
  "Espoo",
  "Drug",
  "Bamenda",
  "Handwara",
  "Lucena",
  "Canton",
  "Yoshkar-Ola",
  "Nalchik",
  "Aswan",
  "Salamanca",
  "Inegol",
  "Chernivtsi",
  "Yao",
  "Sumare",
  "Lubbock",
  "Yanbu`",
  "Sumy",
  "Tshikapa",
  "Anantapur",
  "San Pablo",
  "Reading",
  "Winter Haven",
  "Myeik",
  "Maraba",
  "Kutahya",
  "Salem",
  "Djelfa",
  "Petrolina",
  "Suncheon",
  "St. Petersburg",
  "Dera Ghazi Khan",
  "Kindu",
  "Oruro",
  "Dezful",
  "Osmaniye",
  "Lafayette",
  "Kyongju",
  "Dumai",
  "Kakogawacho-honmachi",
  "Gent",
  "Geelong",
  "Corlu",
  "Nawabshah",
  "Gelsenkirchen",
  "Fukui",
  "Monchengladbach",
  "Bordeaux",
  "Annaba",
  "Venice",
  "Barueri",
  "Nonthaburi",
  "Laredo",
  "Jersey City",
  "Quang Ngai",
  "Concord",
  "Damanhur",
  "Dongta",
  "Ciudad Benito Juarez",
  "Cascavel",
  "Hiratsuka",
  "Columbus",
  "Chandler",
  "Governador Valadares",
  "Sakarya",
  "Tagum",
  "Kunduz",
  "Ciudad Santa Catarina",
  "Los Mochis",
  "Soka",
  "Texcoco",
  "Misratah",
  "Isparta",
  "Etawah",
  "Huayin",
  "McKinney",
  "Playa del Carmen",
  "Scottsdale",
  "Wolverhampton",
  "Killeen",
  "Bergen",
  "Tallahassee",
  "Shinozaki",
  "Horlivka",
  "Antsirabe",
  "Ondo",
  "Hakodate",
  "Ap Da Loi",
  "Foz do Iguacu",
  "Tokushima",
  "Peoria",
  "Santa Maria",
  "Kediri",
  "Fort-de-France",
  "Damaturu",
  "Malolos",
  "La Paz",
  "Wilmington",
  "Raichur",
  "Mawlamyine",
  "Turmero",
  "Kuala Terengganu",
  "Daloa",
  "Puerto Princesa",
  "Qarshi",
  "Montgomery",
  "Gilbert",
  "Rishon LeZiyyon",
  "Ongole",
  "Arua",
  "Verona",
  "Bharatpur",
  "Rach Gia",
  "Kanggye",
  "Taganrog",
  "Buenaventura",
  "Kiziltepe",
  "Vitoria-Gasteiz",
  "El Fasher",
  "Varzea Grande",
  "Glendale",
  "Santiago del Estero",
  "Usak",
  "Begusarai",
  "North Las Vegas",
  "Sonipat",
  "Los Teques",
  "Mabalacat",
  "Jinshi",
  "Osh",
  "Iwo",
  "Bata",
  "Chofugaoka",
  "Komsomol'sk-na-Amure",
  "Babol",
  "Galati",
  "Al Bayda'",
  "Yamagata",
  "Manzhouli",
  "Kiel",
  "Braunschweig",
  "Rivne",
  "Gdynia",
  "Palangkaraya",
  "Al Minya",
  "Hafr al Batin",
  "Caruaru",
  "San Bernardo",
  "Bukan",
  "Aachen",
  "Sahiwal",
  "Chigasaki",
  "Thu Dau Mot",
  "Sibu",
  "Anchorage",
  "Parana",
  "Oruro",
  "Merlo",
  "Syktyvkar",
  "Khimki",
  "Biratnagar",
  "Chemnitz",
  "Saskatoon",
  "Yato",
  "Colon",
  "Abertawe",
  "Fuji",
  "Puerto Montt",
  "Jessore",
  "Beichengqu",
  "Tuy Hoa",
  "Shrirampur",
  "Chesapeake",
  "Hapur",
  "Bahir Dar",
  "Manisa",
  "Tanga",
  "Sabzevar",
  "Ramgundam",
  "Porto",
  "Tacloban",
  "Myitkyina",
  "Barnstable",
  "Haeju",
  "Petah Tiqwa",
  "Norfolk",
  "Gonzalez Catan",
  "Juazeiro do Norte",
  "Diaobingshancun",
  "Tarapoto",
  "Zhangping",
  "San Juan del Rio",
  "Tsukuba-kenkyugakuen-toshi",
  "Sao Carlos",
  "Ilheus",
  "Fremont",
  "Halle",
  "Duzce",
  "Anju",
  "Aarhus",
  "Kennewick",
  "Hobart",
  "Artux",
  "Chimoio",
  "Limassol",
  "Garland",
  "Magdeburg",
  "Irving",
  "Hachimancho",
  "Longueuil",
  "Mokpo",
  "Kosice",
  "`Ajman",
  "Lille",
  "Neya",
  "Banda Aceh",
  "Le Havre",
  "Taiping",
  "P'yong-dong",
  "Springs",
  "Ivano-Frankivsk",
  "As Sib",
  "Narayanganj",
  "Wuyishan",
  "Sato",
  "Amol",
  "Quilmes",
  "Mirpur Khas",
  "Nizhnekamsk",
  "Visalia",
  "Al Jubayl",
  "Pathein",
  "Secunderabad",
  "Chishui",
  "Centurion",
  "Atlantic City",
  "Uluberiya",
  "Shakhty",
  "Messina",
  "Pakdasht",
  "El Tigre",
  "Kremenchuk",
  "Abha",
  "Ibb",
  "Garoua",
  "Bole",
  "Najafabad",
  "Bayamo",
  "Porbandar",
  "Granada",
  "Kamianske",
  "Borujerd",
  "Singaraja",
  "Miri",
  "Machala",
  "Longquan",
  "Monclova",
  "Puducherry",
  "Olongapo",
  "Saga",
  "Nashua",
  "Santarem",
  "Paradise",
  "Okara",
  "Kasukabe",
  "Talisay",
  "Hialeah",
  "Saidpur",
  "York",
  "Burnaby",
  "Rancagua",
  "Dzerzhinsk",
  "Milton Keynes",
  "Marilia",
  "Barishal",
  "Bratsk",
  "Jiayuguan",
  "Arlington",
  "Indaiatuba",
  "Freiburg im Breisgau",
  "Madan",
  "Qarchak",
  "Itabuna",
  "Neuquen",
  "Ibb",
  "Ageoshimo",
  "Badalona",
  "Singkawang",
  "Orsk",
  "Vizianagaram",
  "Evansville",
  "Cotia",
  "North Hempstead",
  "Pali",
  "Noginsk",
  "Kropyvnytskyi",
  "Czestochowa",
  "Guantanamo",
  "Krefeld",
  "Guadalupe",
  "Kolpino",
  "Huixquilucan",
  "Burgas",
  "Puerto Vallarta",
  "Avondale",
  "Nyala",
  "Brownsville",
  "Sakurazuka",
  "Dasoguz",
  "Turkistan",
  "Probolinggo",
  "Atsugicho",
  "Jacarei",
  "Gusau",
  "Buenavista",
  "Quetzaltenango",
  "Araraquara",
  "Angarsk",
  "Nagercoil",
  "Heroica Nogales",
  "Apapa",
  "Nyanza",
  "Itapevi",
  "Bac Lieu",
  "Varamin",
  "Padangsidempuan",
  "Karnal",
  "Mubi",
  "Toamasina",
  "Engels",
  "Campeche",
  "Korolev",
  "Cidade de Nacala",
  "Hunchun",
  "Tampere",
  "Minamiozuma",
  "Blagoveshchensk",
  "Velikiy Novgorod",
  "Ashdod",
  "Carlos Manuel de Cespedes",
  "Nigde",
  "Sandton",
  "Tanjore",
  "Staryy Oskol",
  "Puri",
  "Cartago",
  "Ji'an Shi",
  "Soledad de Graciano Sanchez",
  "Presidente Prudente",
  "Jose C. Paz",
  "Ternopil",
  "Rufisque",
  "Gueckedou",
  "Formosa",
  "Gabes",
  "Imperatriz",
  "Sambhal",
  "Polokwane",
  "Neyshabur",
  "Sidon",
  "Radom",
  "Lutsk",
  "La Serena",
  "Gujiao",
  "Gulfport",
  "San Felipe",
  "Saveh",
  "La Vega",
  "Appleton",
  "Khomeyni Shahr",
  "Al Khubar",
  "Islington",
  "Cordoba",
  "San Pedro de Macoris",
  "Ciudad Acuna",
  "Sabadell",
  "Hortolandia",
  "Bitung",
  "Naihati",
  "Damietta",
  "Groningen",
  "Kure",
  "Manta",
  "Butembo",
  "San Miguel",
  "Concepcion",
  "Netanya",
  "Bremerton",
  "Alor Setar",
  "Hickory",
  "Lubeck",
  "Los Angeles",
  "Aberdeen",
  "Luton",
  "Tacoma",
  "Denov",
  "Qostanay",
  "Banjarbaru",
  "Sa Dec",
  "Norwich",
  "Petropavl",
  "Marg`ilon",
  "Gangneung",
  "San Bernardino",
  "Cua",
  "Meycauayan",
  "Vantaa",
  "As Samawah",
  "Ormoc",
  "College Station",
  "Golmud",
  "Kalamazoo",
  "Cartagena",
  "Regina",
  "Thousand Oaks",
  "La Victoria",
  "Shimla",
  "Mohammedia",
  "Babruysk",
  "Roanoke",
  "Osan",
  "Geneva",
  "Criciuma",
  "Fontana",
  "Sikasso",
  "Warnes",
  "Padova",
  "Ciudad Madero",
  "Oberhausen",
  "Jalalabad",
  "Moreno Valley",
  "Sidi Bel Abbes",
  "Jerez de la Frontera",
  "Limbe",
  "Timon",
  "Ploiesti",
  "Metepec",
  "Pskov",
  "Bila Tserkva",
  "Dayr az Zawr",
  "Babylon",
  "Chungju",
  "San-Pedro",
  "Bukit Mertajam",
  "Ijebu-Ode",
  "Cork",
  "Pamplona",
  "Guarenas",
  "Rostock",
  "Dongning",
  "Moratuwa",
  "Ich'on",
  "Puerto Cabello",
  "Beersheba",
  "Nasim Shahr",
  "North Port",
  "La Romana",
  "Lubuklinggau",
  "Qina",
  "Mary",
  "Santa Cruz",
  "Fargo",
  "Huangyan",
  "Santa Clara",
  "Kharagpur",
  "Northcote",
  "Waitakere",
  "Lobito",
  "Monywa",
  "Dindigul",
  "Morogoro",
  "Green Bay",
  "Portoviejo",
  "Pingzhen",
  "Linz",
  "Trieste",
  "Sacala",
  "Itami",
  "Phan Thiet",
  "Kalemie",
  "Biskra",
  "Ingraj Bazar",
  "Bani Suwayf",
  "Ellore",
  "Mossoro",
  "Mytishchi",
  "Zanzibar",
  "Jiutai",
  "Qa'em Shahr",
  "Bolu",
  "Amarillo",
  "Ziguinchor",
  "Ternate",
  "Puqi",
  "Sete Lagoas",
  "Bene Beraq",
  "Torun",
  "Coquimbo",
  "Mandi Burewala",
  "Kamirenjaku",
  "Marawi City",
  "Erfurt",
  "Portland",
  "Matsue",
  "Biysk",
  "Charleroi",
  "Kassel",
  "Poza Rica de Hidalgo",
  "Tanjungpinang",
  "Zhubei",
  "Djougou",
  "Luxor",
  "Huntington",
  "Tarakan",
  "Santa Barbara",
  "Gainesville",
  "Las Tunas",
  "Lyubertsy",
  "Sosnowiec",
  "Arica",
  "Huacho",
  "Debrecen",
  "Nandyal",
  "Cajamarca",
  "Croydon",
  "Lashkar Gah",
  "Yachiyo",
  "Haldia",
  "San Pablo de las Salinas",
  "Jacobabad",
  "Tokat",
  "Qyzylorda",
  "Nema",
  "Olympia",
  "Gurgaon",
  "Liege",
  "Oulu",
  "El Jadid",
  "Frisco",
  "Isidro Casanova",
  "Maimanah",
  "Yonkers",
  "Rio Claro",
  "Norwich",
  "Az Zawiyah",
  "Bulandshahr",
  "Kasama",
  "Divinopolis",
  "Puerto Cortes",
  "Lahad Datu",
  "Bojnurd",
  "Spring Valley",
  "Pagadian",
  "Nagareyama",
  "Banja Luka",
  "Glendale",
  "Huntington Beach",
  "Almeria",
  "Brescia",
  "Baharampur",
  "Taranto",
  "Ashino",
  "Talca",
  "Martapura",
  "Chakradharpur",
  "Deltona",
  "Chilpancingo",
  "Naga City",
  "Richmond",
  "Holon",
  "Gemena",
  "Tocuyito",
  "Oradea",
  "Legazpi City",
  "Hedong",
  "Madhyamgram",
  "Aurora",
  "Bhiwani",
  "Burhanpur",
  "Mbanza-Ngungu",
  "Huanuco",
  "Prokopyevsk",
  "Rajin",
  "Ghandinagar",
  "Eldoret",
  "Tegucigalpita",
  "Hino",
  "Kusong",
  "Suhaj",
  "Suzuka",
  "Khammam",
  "Kirikkale",
  "Ar Raqqah",
  "Kumagaya",
  "Higashi-Hiroshima",
  "Brikama",
  "Acarigua",
  "Hugli",
  "Viransehir",
  "San Luis Rio Colorado",
  "Iskandar",
  "Tempe",
  "Naka",
  "Kenema",
  "Overland Park",
  "Bandar-e Bushehr",
  "Yamaguchi",
  "Parma",
  "Anseong",
  "Yuzhno-Sakhalinsk",
  "Richmond Hill",
  "Dese",
  "Gorontalo",
  "Cholula de Rivadabia",
  "Guacara",
  "Grand Prairie",
  "Quelimane",
  "Tebessa",
  "San Fernando",
  "Al Jahra'",
  "Karaman",
  "Cap-Haitien",
  "Oakville",
  "Muar",
  "Prato",
  "Godoy Cruz",
  "Mus",
  "Hyesan",
  "Kielce",
  "Arapiraca",
  "Valencia",
  "Sunrise Manor",
  "Aracatuba",
  "Swindon",
  "Guanare",
  "Waco",
  "Basildon",
  "Madiun",
  "Kawara",
  "Gibraltar",
  "Valera",
  "Barrancabermeja",
  "Mahbubnagar",
  "Pasuruan",
  "Aydin",
  "Shibin al Kawm",
  "Armavir",
  "Balakovo",
  "Rio Grande",
  "Batu",
  "Salinas",
  "Mwene-Ditu",
  "Son Tay",
  "Ferraz de Vasconcelos",
  "Santa Barbara d'Oeste",
  "Oviedo",
  "Saddiqabad",
  "Rybinsk",
  "Anjomachi",
  "Chongju",
  "Cachoeiro de Itapemirim",
  "Joetsu",
  "Saint-Denis",
  "Hagen",
  "Ngaoundere",
  "Potosi",
  "San Carlos City",
  "Pak Kret",
  "Waterbury",
  "Donghua",
  "Parakou",
  "Mutare",
  "Kofu",
  "Mataro",
  "Narsingdi",
  "Araure",
  "Tottori",
  "Pinar del Rio",
  "Clarksville",
  "Raiganj",
  "Prabumulih",
  "Tachikawa",
  "Al Hasakah",
  "Turku",
  "Guatire",
  "Iquique",
  "Cedar Rapids",
  "San Diego",
  "Gharyan",
  "Bournemouth",
  "Chaedok",
  "Izuo",
  "La Plata",
  "Prizren",
  "Sioux Falls",
  "Mainz",
  "Cabo Frio",
  "Shendi",
  "Reims",
  "Ed Damazin",
  "Khujand",
  "Huntington",
  "Dunhuang",
  "Mahesana",
  "Modena",
  "Guri",
  "Jamaame",
  "Panabo",
  "Adoni",
  "Temirtau",
  "Basel",
  "Yei",
  "Santo Agostinho",
  "Ontario",
  "Toyokawa",
  "Luzhang",
  "Hagerstown",
  "Al Qamishli",
  "Manzanillo",
  "Erie",
  "Vancouver",
  "Nampa",
  "Fardis",
  "Fianarantsoa",
  "Banjar",
  "Severodvinsk",
  "Rzeszow",
  "Calbayog City",
  "Bhusaval",
  "Trondheim",
  "Uji",
  "Passo Fundo",
  "Aqtau",
  "Reggio di Calabria",
  "Nis",
  "Abakan",
  "Burlington",
  "Bahraigh",
  "Bo",
  "Worthing",
  "Pinrang",
  "Spartanburg",
  "Braila",
  "Nova Friburgo",
  "Gastonia",
  "Amadora",
  "Braga",
  "Fort Lauderdale",
  "Kabankalan",
  "Tonk",
  "Berazategui",
  "Khowy",
  "Sirsa",
  "Narashino",
  "Tangail",
  "Jaunpur",
  "Saarbrucken",
  "Santo Tomas",
  "Petropavlovsk-Kamchatskiy",
  "Sittwe",
  "Phan Rang-Thap Cham",
  "Jima",
  "Townsville",
  "Lhokseumawe",
  "Gliwice",
  "Funtua",
  "Hinthada",
  "La Rioja",
  "Canakkale",
  "Madanapalle",
  "Palopo",
  "Ayacucho",
  "Tunja",
  "Obuase",
  "Alleppey",
  "Ipswich",
  "Boma",
  "Tiaret",
  "Edirne",
  "Chicoloapan",
  "Longjing",
  "Split",
  "Lorain",
  "Klerksdorp",
  "Murfreesboro",
  "High Point",
  "Hamm",
  "Tarija",
  "Al `Arish",
  "El Oued",
  "Paita",
  "Newport News",
  "Torbali",
  "Potsdam",
  "Langsa",
  "Bade",
  "Bida",
  "Salalah",
  "Matosinhos",
  "Baranavichy",
  "Birjand",
  "Vellore",
  "Dam Dam",
  "Bejaia",
  "Rancho Cucamonga",
  "Norilsk",
  "Santander",
  "Hemet",
  "Yangmei",
  "Ciudad Valles",
  "Kadugli",
  "Les Cayes",
  "Hitachi",
  "Sunderland",
  "Letpandan",
  "Kamakurayama",
  "Zabrze",
  "Almada",
  "Ilford",
  "Cuautla",
  "Santa Cruz",
  "Saint-Louis",
  "Barra Mansa",
  "Ait Melloul",
  "Plzen",
  "Ciudad del Carmen",
  "Danbury",
  "Toulon",
  "Peoria",
  "Oeiras",
  "Dagupan City",
  "Eregli",
  "Oceanside",
  "Shibirghan",
  "Chandannagar",
  "Harar",
  "Middlesbrough",
  "Tyre",
  "Koronadal",
  "Olsztyn",
  "Cuddalore",
  "Maragheh",
  "Obiraki",
  "Tebingtinggi",
  "Comitan",
  "San Francisco de Macoris",
  "Takaoka",
  "Sirjan",
  "Tanauan",
  "Menemen",
  "Malaybalay",
  "Elk Grove",
  "Syzran",
  "Carupano",
  "Saint-Etienne",
  "Lagos de Moreno",
  "Leon",
  "Chirala",
  "Titagarh",
  "Bielsko-Biala",
  "Beppucho",
  "Bytom",
  "Linjiang",
  "Ha Long",
  "Deo",
  "Pembroke Pines",
  "Tlemcen",
  "Albacete",
  "Castellon de la Plana",
  "Shahin Shahr",
  "Comodoro Rivadavia",
  "Ludwigshafen",
  "Vallejo",
  "Escuintla",
  "Izumo",
  "Bertoua",
  "Banyuwangi",
  "Mulheim",
  "Sacaba",
  "Carpina",
  "Banha",
  "Barrie",
  "Krasnogorsk",
  "Kaolack",
  "Sakura",
  "Burgos",
  "Guanajuato",
  "Reggio Emilia",
  "Francisco Morato",
  "Garden Grove",
  "Volgodonsk",
  "Bago",
  "Niiza",
  "Toledo",
  "Kamensk-Ural'skiy",
  "Kohat",
  "Nishio",
  "Loja",
  "Cuauhtemoc",
  "Medford",
  "Hamilton",
  "Ussuriysk",
  "Uvira",
  "Portmore",
  "Machilipatnam",
  "Bordj Bou Arreridj",
  "Nukus",
  "Malayer",
  "N'Zerekore",
  "Cary",
  "Kluang",
  "Novocherkassk",
  "Marysville",
  "Digos",
  "San Luis",
  "Corona",
  "Oldenburg",
  "Medinipur",
  "Fenglu",
  "Al Marj",
  "Sosan",
  "Ocala",
  "Sonsonate",
  "Gondomar",
  "Sarh",
  "Jamalpur",
  "Fredericksburg",
  "Sobral",
  "Ambato",
  "Baramula",
  "Roxas City",
  "Sorsogon",
  "Oyama",
  "Takaoka",
  "Tanjungbalai",
  "Huich'on",
  "Uppsala",
  "Itapecerica da Serra",
  "Sao Caetano do Sul",
  "Zlatoust",
  "Rustenburg",
  "Patra",
  "Riohacha",
  "Nador",
  "Iwata",
  "Gainesville",
  "Itu",
  "Fatehpur",
  "`Ar`ar",
  "Ha Tinh",
  "Al Kufah",
  "Kimberley",
  "Tenali",
  "Skikda",
  "Nantou",
  "Siirt",
  "Kuytun",
  "Osnabruck",
  "Rio Largo",
  "Korfez",
  "Perugia",
  "Udipi",
  "Oshawa",
  "Klaipeda",
  "Leverkusen",
  "Tulua",
  "Idlib",
  "Warrington",
  "Sitalpur",
  "Cienfuegos",
  "Bayamon",
  "Proddatur",
  "Conjeeveram",
  "Saqqez",
  "Dourados",
  "Huddersfield",
  "Fukang",
  "Ube",
  "Slough",
  "Bhisho",
  "Chillan",
  "Enterprise",
  "Odense",
  "Metro",
  "Ramat Gan",
  "Muridke",
  "Ipswich",
  "Ruse",
  "Myingyan",
  "Chapeco",
  "Tangjin",
  "Tema",
  "`Unayzah",
  "Barreiras",
  "Piedras Negras",
  "Itapetininga",
  "Pocheon",
  "Turgutlu",
  "Navsari",
  "Wau",
  "Golcuk",
  "Muzaffargarh",
  "Jizzax",
  "Atyrau",
  "Simao",
  "Mostar",
  "El Geneina",
  "Bandar-e Mahshahr",
  "Manchester",
  "Anaco",
  "Sullana",
  "Godhra",
  "Zemun",
  "Mahabad",
  "Budaun",
  "Chittoor",
  "Andong",
  "Ash Shatrah",
  "Mocamedes",
  "Rafsanjan",
  "Benoni",
  "Heidelberg",
  "Al Ghardaqah",
  "Salihli",
  "Elektrostal",
  "Bontang",
  "Dong Hoi",
  "Krishnanagar",
  "Szeged",
  "Sherbrooke",
  "Solingen",
  "Tacheng",
  "Dhamar",
  "Jose Maria Ezeiza",
  "Braganca Paulista",
  "Ra's al Khaymah",
  "Pindamonhangaba",
  "Dijon",
  "Livorno",
  "Khost",
  "Darmstadt",
  "Saint-Marc",
  "Arad",
  "Khanpur",
  "Matsuzaka",
  "Taunggyi",
  "Bingol",
  "San Nicolas de los Arroyos",
  "Huaycan",
  "Tiraspol",
  "Shahr-e Kord",
  "Talas",
  "Punta del Este",
  "Ekibastuz",
  "Trece Martires City",
  "Ogaki",
  "Hat Yai",
  "Chirchiq",
  "Catamarca",
  "Nakhodka",
  "Jijiga",
  "Kramatorsk",
  "Champaign",
  "Alexandria",
  "George",
  "Herne",
  "Ravenna",
  "Zarzis",
  "Hayward",
  "La Laguna",
  "Higashi-murayama",
  "Saharsa",
  "Stara Zagora",
  "Chau Doc",
  "Guimaraes",
  "Haripur",
  "Springfield",
  "San Cristobal",
  "Rafael Castillo",
  "Villanueva",
  "Gojra",
  "Lakewood",
  "Oxford",
  "Villeurbanne",
  "Lafayette",
  "Fethiye",
  "Uiwang",
  "Navojoa",
  "Calama",
  "Erzincan",
  "Middelburg",
  "Mandi Bahauddin",
  "Zonguldak",
  "Hitachi-Naka",
  "Isiro",
  "Jinggangshan",
  "Jiutepec",
  "Batumi",
  "Pathankot",
  "Nazilli",
  "Frederick",
  "Lajes",
  "Pitesti",
  "Chlef",
  "Chetumal",
  "Rondonopolis",
  "Esmeraldas",
  "Angers",
  "Hanam",
  "Daiwanishi",
  "Matagalpa",
  "Salzburg",
  "Vidisha",
  "Cam Pha",
  "Kariya",
  "Tochigi",
  "Lake Charles",
  "Odessa",
  "Nalgonda",
  "Ordu",
  "San Cristobal",
  "Tuscaloosa",
  "Horad Barysaw",
  "Neuss",
  "Miskolc",
  "Warner Robins",
  "Bartin",
  "Palmdale",
  "Melitopol'",
  "Zango",
  "Tama",
  "Hollywood",
  "Balurghat",
  "Midland",
  "Surigao",
  "Dibrugarh",
  "Mahajanga",
  "Salavat",
  "Bandirma",
  "Leesburg",
  "Tuguegarao",
  "Gandajika",
  "Silao",
  "Regensburg",
  "Ueda",
  "Port Arthur",
  "York",
  "Palo Negro",
  "Almetyevsk",
  "Kafr ash Shaykh",
  "Noda",
  "Seogwipo",
  "Moanda",
  "Tete",
  "Mzuzu",
  "Fyzabad",
  "Harrow",
  "Poole",
  "Semnan",
  "Hoeryong",
  "Kirsehir",
  "Muskegon",
  "Sievierodonetsk",
  "Guarapuava",
  "Sinp'o",
  "Silchar",
  "Macon",
  "Kokshetau",
  "Macae",
  "Cairns",
  "Yilan",
  "Papantla de Olarte",
  "Kansas City",
  "Ciudad de Melilla",
  "Shantipur",
  "Kukichuo",
  "Golmeh",
  "Zabid",
  "Peristeri",
  "Hindupur",
  "Sunnyvale",
  "Baubau",
  "Mudon",
  "Sayama",
  "Taza",
  "Settat",
  "Imabari",
  "Foggia",
  "Erode",
  "Pocos de Caldas",
  "Gwangyang",
  "Tororo",
  "Gonbad-e Kavus",
  "Al Manaqil",
  "Miass",
  "Tulancingo",
  "Nimes",
  "Chinandega",
  "Saint Albans",
  "Nakhodka",
  "Quevedo",
  "Bintulu",
  "Pomona",
  "Siem Reap",
  "Escondido",
  "Cao Lanh",
  "Riobamba",
  "Vryheid",
  "As Suwayhirah as Sahil",
  "Paderborn",
  "Zamora",
  "Manzanillo",
  "Pasadena",
  "Florencio Varela",
  "Komaki",
  "Talcahuano",
  "Kerch",
  "Patos de Minas",
  "Copiapo",
  "Badajoz",
  "M'Sila",
  "Kragujevac",
  "Pointe-a-Pitre",
  "Willemstad",
  "Rimini",
  "Dundee",
  "Jijel",
  "Ocumare del Tuy",
  "Valdivia",
  "Gulu",
  "La Ceiba",
  "Shahrud",
  "Iruma",
  "Kashikishi",
  "Sumbawanga",
  "Keren",
  "Odivelas",
  "New Bedford",
  "Jamuria",
  "Kutaisi",
  "Potchefstroom",
  "Shimotoda",
  "Concordia",
  "Abbottabad",
  "Delicias",
  "Mallawi",
  "Agri",
  "Amasya",
  "Lang Son",
  "Salamanca",
  "Kastamonu",
  "Marvdasht",
  "Goma",
  "Yonago",
  "Chingola",
  "Fairfield",
  "Mostaganem",
  "Habra",
  "Mauli",
  "Sibiu",
  "Naperville",
  "Quilpue",
  "Dolores Hidalgo Cuna de la Independencia Nacional",
  "Kopeysk",
  "Luleburgaz",
  "Al Hawiyah",
  "Bellevue",
  "Binghamton",
  "Nchelenge",
  "Negombo",
  "Ambala",
  "Disuq",
  "Mangghystau",
  "Malakal",
  "Bacau",
  "Osorno",
  "Elkhart",
  "Topeka",
  "Mogi Guacu",
  "Man",
  "Joliet",
  "Pyatigorsk",
  "Clermont-Ferrand",
  "Moshi",
  "Dar`a",
  "Rubtsovsk",
  "Cam Ranh",
  "Wamba",
  "Franco da Rocha",
  "Dadu",
  "Sagay",
  "Balti",
  "San Juan",
  "Kolomna",
  "Larisa",
  "Misato",
  "San Miguel de Allende",
  "Beaumont",
  "Paranagua",
  "Garcia",
  "Kakamigahara",
  "Logrono",
  "Matanzas",
  "Ilagan",
  "David",
  "Le Mans",
  "San Justo",
  "Quchan",
  "Berezniki",
  "Shillong",
  "Eregli",
  "Tizi Ouzou",
  "Durres",
  "Yalova",
  "Villa de Cura",
  "Paterson",
  "Merced",
  "Kolar",
  "Cape Coast",
  "Al Mukalla",
  "Dongxing",
  "Comayagua",
  "Barranca",
  "Khasavyurt",
  "Saguenay",
  "Tuxtepec",
  "Kairouan",
  "Marbella",
  "Huelva",
  "Kumba",
  "Parnaiba",
  "Barrechid",
  "Bharatpur",
  "Saida",
  "Kusatsu",
  "Florencia",
  "Pueblo",
  "Pleiku",
  "Coimbra",
  "Ajdabiya",
  "Tyler",
  "Ciego de Avila",
  "Pecs",
  "Ghazni",
  "Blackpool",
  "Nawabganj",
  "Altay",
  "El Progreso",
  "Torrance",
  "Pemba",
  "Jau",
  "Metairie",
  "Touggourt",
  "Tuxpam de Rodriguez Cano",
  "Nevsehir",
  "Bechar",
  "Levis",
  "Bhimavaram",
  "Bilbays",
  "Tottenham",
  "Aix-en-Provence",
  "Cizre",
  "Arnhem",
  "Gisenyi",
  "Fukayacho",
  "Yuma",
  "Telford",
  "Lichinga",
  "Ozamiz City",
  "Moundou",
  "Tetovo",
  "Nizip",
  "Maykop",
  "Lausanne",
  "Kamalshahr",
  "Gweru",
  "Kelowna",
  "Castanhal",
  "Irakleio",
  "Mandsaur",
  "Rybnik",
  "Nong'an",
  "Rize",
  "Vlore",
  "Bizerte",
  "Jahrom",
  "Surprise",
  "Columbia",
  "Colima",
  "Ishizaki",
  "Athens",
  "Roseville",
  "Thornton",
  "Khuzdar",
  "Tepatitlan de Morelos",
  "Abbotsford",
  "Mati",
  "Ruda Slaska",
  "Miramar",
  "Batu Pahat",
  "Schaarbeek",
  "Pasadena",
  "Kovrov",
  "Mesquite",
  "Odintsovo",
  "Kuwana",
  "Kidapawan",
  "Santa Maria",
  "Olathe",
  "Masaya",
  "Medea",
  "Yaritagua",
  "San Jose",
  "Houma",
  "Samarra'",
  "Koga",
  "Sale",
  "Carolina",
  "Al `Aqabah",
  "Torbat-e Heydariyeh",
  "Dawei",
  "Boulogne-Billancourt",
  "Zielona Gora",
  "Atbara",
  "Tours",
  "Pakpattan",
  "Shizuishan",
  "Tsuchiura",
  "Chicacole",
  "Botucatu",
  "Dhahran",
  "Pabna",
  "Coquitlam",
  "Carrollton",
  "Tan An",
  "Souk Ahras",
  "Caxias",
  "Grand Junction",
  "Zacatecas",
  "Barahona",
  "Kokubunji",
  "Piranshahr",
  "Tiruvannamalai",
  "Amiens",
  "Umtata",
  "Charleston",
  "Orange",
  "Fullerton",
  "Sancti Spiritus",
  "Boulogne-sur-Mer",
  "Jequie",
  "Bat Yam",
  "Boca del Rio",
  "Mojokerto",
  "Darwin",
  "Zama",
  "Ingolstadt",
  "Mandya",
  "Greeley",
  "Ch'ungmu",
  "Al Khmissat",
  "Birganj",
  "Igdir",
  "Lira",
  "Jicheon",
  "Yaizu",
  "Gunungsitoli",
  "Danao",
  "Yunxian Chengguanzhen",
  "Atibaia",
  "Jyvaskyla",
  "Bankura",
  "Inazawa",
  "Salerno",
  "Vila Franca de Xira",
  "Quillacollo",
  "Santa Maria Texmelucan",
  "Livingstone",
  "Toowoomba",
  "Bima",
  "Porto Amboim",
  "Maia",
  "Tarragona",
  "Encarnacion",
  "Kisarazu",
  "Marivan",
  "Uppsala",
  "Chech'on",
  "Jinotega",
  "Pageralam",
  "Giresun",
  "Termiz",
  "Zinacantepec",
  "Targu-Mures",
  "Las Cruces",
  "'s-Hertogenbosch",
  "Panama City",
  "Blitar",
  "Harlingen",
  "Chiang Mai",
  "Brighton",
  "Tobruk",
  "Tauranga",
  "Pyay",
  "Cartago",
  "Santiago",
  "May Pen",
  "Urganch",
  "Zakhu",
  "Dumaguete City",
  "West Valley City",
  "Shuangcheng",
  "Andimeshk",
  "Ome",
  "Tabaco",
  "Nakhon Ratchasima",
  "Isahaya",
  "Ashqelon",
  "Shahreza",
  "Zabol",
  "Ramapo",
  "Hampton",
  "Calapan",
  "Trois-Rivieres",
  "Urdaneta",
  "Milagro",
  "Heroica Guaymas",
  "Apatzingan de la Constitucion",
  "Batticaloa",
  "Rehovot",
  "Abiko",
  "Idfu",
  "Tando Allahyar",
  "Warren",
  "Mauldin",
  "Bloomington",
  "Enfield",
  "Segou",
  "Coral Springs",
  "Innsbruck",
  "Battambang",
  "Hassan",
  "Round Rock",
  "Yakima",
  "Khorramshahr",
  "Onomichi",
  "Papeete",
  "Ouargla",
  "Tra Vinh",
  "Narita",
  "Ninh Binh",
  "San Carlos",
  "Gyor",
  "Odemis",
  "Kamez",
  "San Luis",
  "Ibarra",
  "Sterling Heights",
  "Stavanger",
  "Yavatmal",
  "Ferrara",
  "Kent",
  "Karabuk",
  "High Wycombe",
  "Jaragua do Sul",
  "Calabozo",
  "Lae",
  "Kigoma",
  "Pilibhit",
  "Guelph",
  "Palghat",
  "Buea",
  "Los Guayos",
  "Rijeka",
  "Spanish Town",
  "Palakollu",
  "Kislovodsk",
  "Dipolog",
  "Surat Thani",
  "Cienaga",
  "Parepare",
  "Girardot",
  "Burlington",
  "Abohar",
  "Tychy",
  "Marand",
  "Quibdo",
  "Kanchrapara",
  "Annecy",
  "Bellingham",
  "Kozan",
  "Udon Thani",
  "Iwakuni",
  "Jiroft",
  "Tabora",
  "Santa Clara",
  "Vasteras",
  "Cayirova",
  "Sannar",
  "Lucheng",
  "Racine",
  "Greenville",
  "Esteli",
  "Taldyqorghan",
  "Cambridge",
  "Calabayan",
  "Baidoa",
  "Jaramana",
  "Furth",
  "Serpukhov",
  "Bolton",
  "Tukuyu",
  "Stamford",
  "Villa Alemana",
  "Kadoma",
  "Tariba",
  "Wurzburg",
  "Songnim",
  "Mansa",
  "Elizabeth",
  "Opole",
  "Novocheboksarsk",
  "Araras",
  "Romford",
  "Mit Ghamr",
  "Puno",
  "Jaranwala",
  "Salto",
  "Newport",
  "Alagoinhas",
  "Omiyacho",
  "Kamina",
  "Seto",
  "Pinsk",
  "Vihari",
  "Porto Seguro",
  "Koforidua",
  "Ixtlahuaca",
  "Temperley",
  "Bataysk",
  "Whitby",
  "Sakaka",
  "Tumen",
  "Orebro",
  "My Tho",
  "Hathras",
  "Divo",
  "Guasdualito",
  "Domodedovo",
  "Darnah",
  "Port Blair",
  "Cubatao",
  "Jazan",
  "Anderlecht",
  "Alipur Duar",
  "Neftekamsk",
  "Johnson City",
  "Silay",
  "Chilapa de Alvarez",
  "Leon",
  "Bam",
  "Ulm",
  "Lafia",
  "Tay Ninh",
  "Iizuka",
  "Santana de Parnaiba",
  "Heilbronn",
  "Rustavi",
  "Pakokku",
  "Payakumbuh",
  "Angren",
  "Sogamoso",
  "Leiria",
  "Basirhat",
  "Miramar",
  "Leeuwarden",
  "Gafsa",
  "Unye",
  "Ramos Mejia",
  "Navadwip",
  "Pforzheim",
  "Exeter",
  "Lynchburg",
  "Guntakal",
  "Pangkalpinang",
  "Latina",
  "Simi Valley",
  "Daitocho",
  "Aalborg",
  "Guelma",
  "Barbacena",
  "Monza",
  "Tengyue",
  "Solihull",
  "Dunedin",
  "Halisahar",
  "Nefteyugansk",
  "Magway",
  "Shashemene",
  "Rishra",
  "Malanje",
  "Magelang",
  "Gashua",
  "Shchelkovo",
  "Kampong Cham",
  "Santa Tecla",
  "Novomoskovsk",
  "Gorzow Wielkopolski",
  "Cam Ranh",
  "Giugliano in Campania",
  "Kumbo",
  "Cagua",
  "Cadiz",
  "Jandira",
  "Ghardaia",
  "Gateshead",
  "Honcho",
  "Uruguaiana",
  "Curico",
  "Orizaba",
  "Ciudad de Atlixco",
  "Fort Smith",
  "Resende",
  "Polatli",
  "Porlamar",
  "Kenosha",
  "Amherst",
  "Gingoog",
  "Duma",
  "Wolfsburg",
  "South Lyon",
  "Pouso Alegre",
  "Maastricht",
  "Pervouralsk",
  "Hosan",
  "Ise",
  "Boulder",
  "Bimbo",
  "Baia Mare",
  "Savannakhet",
  "Al Hajar al Aswad",
  "Kadirli",
  "Brits",
  "Cherkessk",
  "Indramayu",
  "Higuey",
  "Rudnyy",
  "Khrustalnyi",
  "Honmachi",
  "Pescara",
  "San Pedro Garza Garcia",
  "Pleven",
  "Hoi An",
  "Derbent",
  "Preston",
  "Villa de Alvarez",
  "Pati",
  "Tsuruoka",
  "Munuf",
  "Gagnoa",
  "Punta Arenas",
  "Dabrowa Gornicza",
  "Munch'on",
  "Khenifra",
  "Alberton",
  "Lianhe",
  "San Fernando",
  "Jirja",
  "Patnos",
  "Bergamo",
  "Blackburn",
  "Barretos",
  "Machiques",
  "Ciudad Hidalgo",
  "Jalapa",
  "Yonashiro-teruma",
  "Behbahan",
  "Elblag",
  "Baidyabati",
  "Pearland",
  "Mufulira",
  "Maina",
  "Kashiwara",
  "Kotamobagu",
  "Dharmavaram",
  "Edea",
  "Setubal",
  "Montreuil",
  "Ciudad Ojeda",
  "Pedro Juan Caballero",
  "Fier",
  "Orekhovo-Zuyevo",
  "Kamalia",
  "Gyumri",
  "Hoa Binh",
  "Perpignan",
  "Larache",
  "Siracusa",
  "Dorud",
  "Puerto Barrios",
  "Ribeirao Pires",
  "Samandag",
  "Upington",
  "Walthamstow",
  "Berkeley",
  "Plock",
  "Richardson",
  "Dogubayazit",
  "Redding",
  "Arvada",
  "Valinhos",
  "St. George",
  "Kot Addu",
  "Kallithea",
  "Gottingen",
  "Pakxe",
  "Billings",
  "Carcar",
  "Handa",
  "Gao",
  "Guelmim",
  "Puerto Plata",
  "Darjeeling",
  "Yuba City",
  "Mohammad Shahr",
  "Sertaozinho",
  "Fujimino",
  "Poa",
  "Ebetsu",
  "Saint-Denis",
  "San Carlos",
  "Ciudad Choluteca",
  "Varzea Paulista",
  "Rochester",
  "Kaspiysk",
  "Zahle",
  "East Los Angeles",
  "Gudivada",
  "Nazarabad",
  "Leominster",
  "Ajax",
  "Kingsport",
  "Butwal",
  "Nouadhibou",
  "Duluth",
  "Nobeoka",
  "Beppu",
  "Nazran",
  "Sopur",
  "Iguala de la Independencia",
  "Guaratingueta",
  "Lehigh Acres",
  "Huaraz",
  "Konosu",
  "Rock Hill",
  "Ikoma",
  "Gilroy",
  "Cheltenham",
  "Cambridge",
  "Nevinnomyssk",
  "Bruges",
  "Lahti",
  "Reutov",
  "Bandundu",
  "Charallave",
  "Nowshera",
  "Dharan",
  "Anuradhapura",
  "Birigui",
  "Bottrop",
  "Santa Cruz do Sul",
  "Sugar Land",
  "Akishima",
  "Karatepe",
  "Forli",
  "Cuautitlan",
  "Tecoman",
  "Giyon",
  "Texas City",
  "Bama",
  "Bayawan",
  "Iowa City",
  "Saginaw",
  "Trento",
  "Kabwe",
  "Jalingo",
  "Luanshya",
  "Agadez",
  "Uzhhorod",
  "Besancon",
  "Adilabad",
  "Obninsk",
  "Chico",
  "San Martin",
  "Kapakli",
  "Basingstoke",
  "Walbrzych",
  "Maidstone",
  "Xai-Xai",
  "Linkoping",
  "Reutlingen",
  "Langley",
  "Dover",
  "Temixco",
  "Belfort",
  "Kindia",
  "Narasaraopet",
  "Nyiregyhaza",
  "Kyzyl",
  "Conselheiro Lafaiete",
  "Machakos",
  "Nkongsamba",
  "Smithtown",
  "Norman",
  "Mendoza",
  "Clearwater",
  "Tandil",
  "Manp'o",
  "Koencho",
  "Buzau",
  "Araguari",
  "Tatui",
  "Niihama",
  "Naga",
  "Dimitrovgrad",
  "Port-Gentil",
  "Sassari",
  "Coeur d'Alene",
  "Ponce",
  "Chittaurgarh",
  "Seaside",
  "Independence",
  "Argenteuil",
  "Boke",
  "West Jordan",
  "Abilene",
  "Phatthaya",
  "Khon Kaen",
  "Ramenskoye",
  "Nasushiobara",
  "Kilis",
  "Shibuya",
  "Nabeul",
  "Parral",
  "Swabi",
  "Sano",
  "Huejutla de Reyes",
  "Sabha",
  "Tahoua",
  "Chelmsford",
  "Doncaster",
  "Valle de La Pascua",
  "Bloomington",
  "Toliara",
  "Garanhuns",
  "Berdyans'k",
  "El Monte",
  "Otaru",
  "Carlsbad",
  "North Charleston",
  "Bansbaria",
  "Puerto Madryn",
  "Helsingborg",
  "Nagahama",
  "Hatsukaichi",
  "Sloviansk",
  "Koblenz",
  "Oktyabr'skiy",
  "Maribor",
  "St. Cloud",
  "Salto",
  "Zhijiang",
  "Chorzow",
  "Hofu",
  "Las Delicias",
  "Lilan",
  "Bijeljina",
  "Temecula",
  "Bremerhaven",
  "Kamagaya",
  "Bet Shemesh",
  "Ciudad de la Costa",
  "Clovis",
  "Bernal",
  "Valparai",
  "Iringa",
  "Kandy",
  "Hikone",
  "Cuito",
  "Oshu",
  "Nikopol'",
  "Laghouat",
  "Meridian",
  "Saanich",
  "Asela",
  "Kankan",
  "Kusadasi",
  "Jounie",
  "Colchester",
  "Recklinghausen",
  "Pul-e Khumri",
  "Tawau",
  "San Francisco del Rincon",
  "Vicenza",
  "Paarl",
  "Iranshahr",
  "Sorum",
  "Habikino",
  "Itatiba",
  "Uba",
  "Caraguatatuba",
  "Bukittinggi",
  "Higashiomi",
  "Wythenshawe",
  "Erlangen",
  "Sa-ch'on",
  "Kipushi",
  "Linhares",
  "Catanduva",
  "Akcakale",
  "Bergisch Gladbach",
  "City of Isabela",
  "Brandon",
  "Jaen",
  "Novyy Urengoy",
  "Montero",
  "Burdur",
  "Westminster",
  "Castelar",
  "Sokode",
  "Costa Mesa",
  "Rotherham",
  "Hualien",
  "San Carlos de Bariloche",
  "Tondabayashicho",
  "Monroe",
  "Zwolle",
  "Utica",
  "Santa Lucia",
  "Carora",
  "Khenchela",
  "Iriga City",
  "Champdani",
  "Remscheid",
  "Kamyshin",
  "Osmanabad",
  "Algeciras",
  "Esteban Echeverria",
  "Dolgoprudnyy",
  "Shkoder",
  "Jena",
  "Mopti",
  "Kars",
  "Olmaliq",
  "Cavite City",
  "Kuopio",
  "Ciudad Mante",
  "Pompano Beach",
  "Tablada",
  "Laoag",
  "Zhukovskiy",
  "West Palm Beach",
  "Funchal",
  "Ligao",
  "Kuqa",
  "Nsukka",
  "Escuintla",
  "Kazo",
  "Hounslow",
  "Terni",
  "Waterloo",
  "Trier",
  "Terrebonne",
  "Namur",
  "Rochdale",
  "Murom",
  "Bedford",
  "Everett",
  "Manzini",
  "El Centro",
  "Villa Mercedes",
  "Winterthur",
  "Jawhar",
  "Sandacho",
  "Tuzla",
  "Tarnow",
  "Santa Fe",
  "Khardah",
  "Gapan",
  "Nguru",
  "Downey",
  "Stockport",
  "Kecskemet",
  "Lowell",
  "Ahuachapan",
  "Fresnillo",
  "Centennial",
  "Wloclawek",
  "Fasa",
  "As Salamiyah",
  "Yessentuki",
  "Elgin",
  "Tabuk",
  "Kiffa",
  "Dali",
  "Yenangyaung",
  "Ourinhos",
  "Quibor",
  "Borazjan",
  "Richmond",
  "Shinyanga",
  "Ash Shaykh `Uthman",
  "Genhe",
  "Montego Bay",
  "Jeonghae",
  "Shirayamamachi",
  "Baneh",
  "Mascara",
  "Darlington",
  "Broken Arrow",
  "Tinaquillo",
  "Milton",
  "Yoju",
  "Bangaon",
  "Miami Gardens",
  "Bage",
  "Pisco",
  "Dera Ismail Khan",
  "Taitung",
  "Mineshita",
  "The Woodlands",
  "Bend",
  "Burlington",
  "Kandi",
  "Taourirt",
  "Apucarana",
  "Koszalin",
  "Baybay",
  "Labe",
  "Jurupa Valley",
  "Gualeguaychu",
  "Caen",
  "Botosani",
  "Sandy Springs",
  "Yongju",
  "Gresham",
  "Uitenhage",
  "Bukoba",
  "Corumba",
  "Maxixe",
  "Lewisville",
  "Ipiales",
  "Hillsboro",
  "Soma",
  "San Buenaventura",
  "Musoma",
  "Novoshakhtinsk",
  "Crawley",
  "Ferizaj",
  "Ikeda",
  "St. John's",
  "Jacksonville",
  "Salford",
  "Wembley",
  "Pottstown",
  "Tajimi",
  "Moncton",
  "Tadpatri",
  "Huauchinango",
  "Yasuj",
  "Jalpaiguri",
  "Dagenham",
  "Barletta",
  "Birnin Kebbi",
  "Siauliai",
  "Seversk",
  "Teofilo Otoni",
  "El Limon",
  "Inglewood",
  "Orsha",
  "An Nuhud",
  "San Rafael",
  "Tagbilaran City",
  "Thunder Bay",
  "Pavlohrad",
  "Spring Hill",
  "Yevpatoriya",
  "Douliu",
  "Juazeiro",
  "Chaman",
  "Queenstown",
  "Umm Qasr",
  "Sliven",
  "Suriapet",
  "Kogon Shahri",
  "League City",
  "Kefar Sava",
  "Alchevsk",
  "Gillingham",
  "Eau Claire",
  "Bolzano",
  "Charsadda",
  "Roubaix",
  "Turlock",
  "Temple",
  "La Piedad",
  "Himamaylan",
  "Mansfield",
  "Mmabatho",
  "Ilebo",
  "Taungoo",
  "Dieppe",
  "Arzamas",
  "Moron",
  "Longjiang",
  "San Felipe",
  "Songea",
  "Artem",
  "Noyabrsk",
  "Nakhon Si Thammarat",
  "Petrzalka",
  "Chabahar",
  "Raba",
  "La Banda",
  "Ourense",
  "Sioux City",
  "Kemalpasa",
  "Salisbury",
  "Vinh Long",
  "Ballarat",
  "Davie",
  "Achinsk",
  "Daly City",
  "Toride",
  "Subotica",
  "Nusaybin",
  "Trincomalee",
  "Akhmim",
  "Azare",
  "Brovary",
  "Yelets",
  "Pushkino",
  "Liberec",
  "Mazyr",
  "Tikrit",
  "Robat Karim",
  "Koutiala",
  "Passos",
  "Lerma",
  "Ciudad Rio Bravo",
  "Allen",
  "Tarim",
  "Kroonstad",
  "Kandhkot",
  "Granada",
  "Novara",
  "Kongolo",
  "Moers",
  "Kalisz",
  "Saijo",
  "Yozgat",
  "Highlands Ranch",
  "Al Faw",
  "West Covina",
  "Salzgitter",
  "Berdsk",
  "Sparks",
  "Waterloo",
  "Galle",
  "Tadepallegudem",
  "Zomba",
  "Dobrich",
  "Sergiyev Posad",
  "Konotop",
  "Courbevoic",
  "Zihuatanejo",
  "Bouskoura",
  "Lysychansk",
  "Khak-e `Ali",
  "Maumere",
  "Samal",
  "Girona",
  "San Mateo",
  "Villa Luzuriaga",
  "Eastbourne",
  "Worcester",
  "Caseros",
  "Fyfield",
  "Tula de Allende",
  "Catbalogan",
  "Chongshan",
  "Abengourou",
  "Lower Hutt",
  "Kalyani",
  "Kilinochchi",
  "Sakado",
  "Isehara",
  "Piacenza",
  "Ed Damer",
  "Norwalk",
  "Santa Rosa",
  "Dolisie",
  "Negapatam",
  "Wigan",
  "Tourcoing",
  "Osijek",
  "Ariana",
  "Siegen",
  "Gardez",
  "Biak",
  "Columbia",
  "Elista",
  "Libertad",
  "Rialto",
  "Thika",
  "Manteca",
  "Araxa",
  "Bumba",
  "Bayugan",
  "Burzaco",
  "Talara",
  "Novokuybyshevsk",
  "Bergama",
  "Miryang",
  "Nyeri",
  "Satu Mare",
  "Houzhuang",
  "Hildesheim",
  "Ginowan",
  "Sangju",
  "Kirklareli",
  "Hove",
  "Legnica",
  "Nanterre",
  "Bhadreswar",
  "Noginsk",
  "Nikaia",
  "Lida",
  "Saint Helens",
  "Talisay",
  "El Cajon",
  "Bethal",
  "Mumias",
  "Burbank",
  "Longmont",
  "Yunfu",
  "Mayari",
  "Mositai",
  "Dhangadhi",
  "Kashmar",
  "San Felipe del Progreso",
  "Klagenfurt",
  "Delta",
  "Chilakalurupet",
  "Coatepec",
  "Sabratah",
  "Trindade",
  "Boryeong",
  "Shushtar",
  "Santo Antonio de Jesus",
  "Teluk Intan",
  "Hemel Hempstead",
  "Assis",
  "Berisso",
  "Renton",
  "Inzai",
  "Duitama",
  "Chatham",
  "`Ibri",
  "Vista",
  "Olomouc",
  "Zheleznogorsk",
  "Logan",
  "Patos",
  "Sungai Penuh",
  "Vitry-sur-Seine",
  "Tizayuca",
  "Socopo",
  "Prescott Valley",
  "Ancona",
  "Trinidad",
  "Salihorsk",
  "Vacaville",
  "San Luis de la Paz",
  "Wakefield",
  "Chikusei",
  "Oued Zem",
  "Kani",
  "Edinburg",
  "Konan",
  "Mishan",
  "Gutersloh",
  "Sakata",
  "Carmel",
  "Spokane Valley",
  "Oum el Bouaghi",
  "Watford",
  "Jilotepec",
  "Navapolatsk",
  "Cottbus",
  "Edison",
  "Kpalime",
  "San Angelo",
  "Lakewood",
  "Kaiserslautern",
  "Gangtok",
  "La Crosse",
  "Ahar",
  "Diourbel",
  "Andria",
  "Tsuyama",
  "Arden-Arcade",
  "Masjed Soleyman",
  "Mairipora",
  "Torbat-e Jam",
  "Magangue",
  "Kam'yanets'-Podil's'kyy",
  "Idaho Falls",
  "Holland",
  "Red Deer",
  "Charlottesville",
  "Drohobych",
  "Shahrisabz",
  "Lincoln",
  "Longview",
  "Woodbridge",
  "Tracy",
  "Kamloops",
  "Bento Goncalves",
  "Ramnicu Valcea",
  "Erechim",
  "Kettering",
  "Viseu",
  "Kohima",
  "Mingacevir",
  "Janakpur",
  "Chipata",
  "Tultepec",
  "Ciudad General Belgrano",
  "Khanty-Mansiysk",
  "Creteil",
  "Bismarck",
  "Herzliyya",
  "Yen Bai",
  "Shumen",
  "Orem",
  "Yashio",
  "Half Way Tree",
  "Vi Thanh",
  "Tumbes",
  "Malindi",
  "Szekesfehervar",
  "Xirdalan",
  "Tenancingo",
  "Ponta Pora",
  "Wangqing",
  "Sibolga",
  "Aubervilliers",
  "Balanga",
  "Bunia",
  "Arauca",
  "Totonicapan",
  "Sidi Slimane",
  "Peje",
  "Yishui",
  "Fulham",
  "Muriae",
  "Schwerin",
  "San Francisco Solano",
  "Tartu",
  "Zifta",
  "Ceske Budejovice",
  "Colombes",
  "Cankiri",
  "East Ham",
  "Masbate",
  "Kakamega",
  "Rio Gallegos",
  "Ludwigsburg",
  "Compton",
  "Errachidia",
  "Esslingen",
  "Al Bahah",
  "Yotsukaido",
  "Sunrise",
  "Noumea",
  "Barnsley",
  "Hartlepool",
  "Obu",
  "Gjakove",
  "Mtwara",
  "Ealing",
  "Birkenhead",
  "Guercif",
  "Quincy",
  "Lynn",
  "Monte Chingolo",
  "Drobeta-Turnu Severin",
  "Nisshin",
  "Haskovo",
  "Suceava",
  "Hradec Kralove",
  "Al Fujayrah",
  "Usti nad Labem",
  "Ciudad Lazaro Cardenas",
  "Sirnak",
  "South Gate",
  "Miaoli",
  "Makeni",
  "Nuneaton",
  "Itanhaem",
  "Brixton",
  "Kirkland",
  "Levallois-Perret",
  "Brusque",
  "Santiago de Compostela",
  "Magadan",
  "Pardubice",
  "Bender",
  "Panevezys",
  "Jaffna",
  "Bromley",
  "Abaetetuba",
  "Queluz",
  "Bath",
  "Santana",
  "`Amran",
  "Edmonton",
  "Lqoliaa",
  "Hayes",
  "Lobnya",
  "Francistown",
  "Catanzaro",
  "Aulnay-sous-Bois",
  "Jonkoping",
  "Germantown",
  "Babahoyo",
  "Takasagocho-takasemachi",
  "Glyfada",
  "Cadereyta Jimenez",
  "Westminster",
  "Remedios de Escalada",
  "Vanadzor",
  "Kitanagoya",
  "Higashiyamato",
  "Tartus",
  "Valjevo",
  "Santa Monica",
  "Poitiers",
  "Acayucan",
  "Gjilan",
  "Jalal-Abad",
  "Umea",
  "Presov",
  "Balkanabat",
  "Mechelen",
  "Mukacheve",
  "As Salt",
  "Ciudad de Ceuta",
  "Versailles",
  "Caceres",
  "Volos",
  "Carrieres-sur-Seine",
  "Paulo Afonso",
  "Viana do Castelo",
  "Woolwich",
  "Miami Beach",
  "San Leandro",
  "Bracknell",
  "Podujeve",
  "Apizaco",
  "Coronel Oviedo",
  "Codo",
  "Fuentes del Valle",
  "Ebolowa",
  "San Juan de los Morros",
  "Citrus Heights",
  "State College",
  "Koudougou",
  "Darayya",
  "Lokossa",
  "Salina Cruz",
  "Concepcion",
  "Jalpa de Mendez",
  "Mardin",
  "Nakhon Sawan",
  "Como",
  "Nacajuca",
  "Cardenas",
  "Loznica",
  "Edgware",
  "Tucupita",
  "Nabatiye",
  "Kanasin",
  "Ezpeleta",
  "Derry",
  "Piatra Neamt",
  "Ath Thawrah",
  "Hawthorne",
  "Lavras",
  "Avare",
  "Busto Arsizio",
  "Maasin",
  "Kouvola",
  "Kuznetsk",
  "Owariasahi",
  "Daugavpils",
  "Ciudad Lerdo",
  "Issy-les-Moulineaux",
  "Pori",
  "Scunthorpe",
  "Yambol",
  "Louga",
  "Manfalut",
  "Whittier",
  "Clifton",
  "Puerto Maldonado",
  "Hetauda",
  "Formosa",
  "Chaguanas",
  "Cunduacan",
  "Chimaltenango",
  "Pazardzhik",
  "Uman'",
  "Nagaoka",
  "Nazareth",
  "Ivanteyevka",
  "Tucurui",
  "Chervonohrad",
  "Cozumel",
  "Cukai",
  "Mbarara",
  "Champigny-sur-Marne",
  "Lucerne",
  "Mitrovice",
  "Cabo San Lucas",
  "Rivera",
  "Kunitachi",
  "Saint-Ouen",
  "Ouidah",
  "Newmarket",
  "Bitola",
  "Itumbiara",
  "Milpitas",
  "Pernik",
  "Clichy",
  "Phuket",
  "Ho",
  "West Bromwich",
  "Alhambra",
  "Zilina",
  "Resita",
  "Shinkai",
  "Chatham",
  "Rueil-Malmaison",
  "Antsiranana",
  "Dudley",
  "Itauna",
  "Ban Talat Rangsit",
  "Lodwar",
  "Targu Jiu",
  "Zacatlan",
  "Upper Darby",
  "Abomey",
  "Mountain View",
  "Blagoevgrad",
  "Kasserine",
  "Elbasan",
  "Al Muharraq",
  "White Rock",
  "Nea Ionia",
  "Kayes",
  "Sao Mateus",
  "South Shields",
  "Paisley",
  "Weston-super-Mare",
  "Goiana",
  "Bilecik",
  "Juchitan de Zaragoza",
  "Buena Park",
  "Saint-Maur-des-Fosses",
  "Hakkari",
  "Somerville",
  "Chalandri",
  "Bury",
  "Tres Lagoas",
  "Jatai",
  "Gravesend",
  "Aviles",
  "Deerfield Beach",
  "Targoviste",
  "Altamira",
  "Galway",
  "Natitingou",
  "Sao Joao del Rei",
  "Barreiro",
  "Paysandu",
  "Cicero",
  "Atakpame",
  "Focsani",
  "Palmerston North",
  "Iguatu",
  "Drancy",
  "Adigrat",
  "Zuwarah",
  "Shancheng",
  "Sidi Qacem",
  "Puerto Ayacucho",
  "Lawrence",
  "Erdenet",
  "Rubi",
  "Temoaya",
  "Ouahigouya",
  "Silver Spring",
  "Nakhon Pathom",
  "Lowestoft",
  "Pau",
  "Tejupilco",
  "Cheyenne",
  "Ubon Ratchathani",
  "Tustin",
  "Lakewood",
  "Carlisle",
  "Lisala",
  "Szombathely",
  "Banska Bystrica",
  "Ra`ananna",
  "Harrogate",
  "Aveiro",
  "Tambacounda",
  "Newcastle under Lyme",
  "Inowroclaw",
  "New Rochelle",
  "Kensington",
  "La Rochelle",
  "Lebanon",
  "East Kilbride",
  "Wa",
  "Nitra",
  "Lomas del Mirador",
  "Maghaghah",
  "Mpanda",
  "Bacabal",
  "Gladbeck",
  "Sankt Gallen",
  "Cachoeira do Sul",
  "Campo Mourao",
  "Cannes",
  "Alameda",
  "Thornton Heath",
  "Watsonville",
  "Taluqan",
  "Juventino Rosas",
  "Jinja",
  "Davis",
  "Berberati",
  "Esbjerg",
  "Zrenjanin",
  "Las Piedras",
  "Surt",
  "Tamazunchale",
  "Pancevo",
  "Chiryu",
  "Abeche",
  "Bellflower",
  "Ashford",
  "Bokhtar",
  "Musashimurayama",
  "Nek'emte",
  "Calais",
  "Tamanrasset",
  "Ramla",
  "Montrouge",
  "Zadar",
  "Southall",
  "Guamuchil",
  "Quang Tri",
  "Antibes",
  "Zlin",
  "Paracatu",
  "Bistrita",
  "Tissemsilt",
  "Pine Hills",
  "Joensuu",
  "Bella Vista",
  "Rugby",
  "Darhan",
  "Centreville",
  "Guasave",
  "Teyateyaneng",
  "Burton upon Trent",
  "Karlstad",
  "Uxbridge",
  "Baldwin Park",
  "Rioverde",
  "Toledo",
  "Prey Veng",
  "Caguas",
  "Parintins",
  "Kiyosu",
  "Hekinan",
  "Crewe",
  "Matehuala",
  "San Andres",
  "Ijui",
  "Naxcivan",
  "Garissa",
  "Manokwari",
  "Masvingo",
  "Vincennes",
  "Assab",
  "Gosport",
  "Wandsworth",
  "Porto Uniao",
  "Salima",
  "Tulcea",
  "Birobidzhan",
  "Tsurugashima",
  "Yoshikawa",
  "Cabadbaran",
  "Kirtipur",
  "Irece",
  "Yawata-shimizui",
  "Frontera",
  "Neuilly-sur-Seine",
  "Farah",
  "Warzat",
  "Finchley",
  "Monastir",
  "Camden",
  "Evanston",
  "Havirov",
  "Skien",
  "Noisy-le-Grand",
  "Kismaayo",
  "San Juan",
];
